### ISSUE TITLE
McMMO treefeller not getting ignored by AntiCheat.

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#10]
When players use the mcmmo ability treefeller they get immediately a medium warning and right after a high warning.
Hope this can be fixed asap.

**Comment by ZathrasNotTheOne** [comment]
Same here.

**Comment by ImShady** [comment]
I third this.

**Comment by ZathrasNotTheOne** [comment]
Additional data points, common messages triggered include:
xxxx tried to break a block of LOG too fast.
xxxx tried to break a block of LEAVES too fast.
xxxx tried to break a block of LEAVES that was too far away.

**Comment by gravitylow** [comment]
This is a confirmed bug and we are probably going to solve it using the mcMMO API, more info to come soon on this.

**Comment by Rojoss** [comment]
Thanks :)

**Comment by gravitylow** [comment]
Fixed in http://ci.h31ix.net/job/AntiCheat/137/

**Comment by Rojoss** [comment]
Seems to be better.
But still giving some errors like:
[WARNING] [AC] {name} tried to break a block of LOG without swinging their arm.
[WARNING] [AC] {name} tried to break a block of LOG without swinging their arm.
[WARNING] [AC] {name} tried to break a block of LEAVES that was too far away.
[WARNING] [AC] {name} tried to break a block of LEAVES that was too far away.
[WARNING] [AC] {name} tried to break a block of LEAVES that was too far away.
[WARNING] [AC] {name} tried to break a block of LEAVES that was too far away.
[WARNING] [AC] {name} tried to break a block of LEAVES that was too far away.

Also i can't reopen the issue anymore :O
Please don't close it to fast or allow us to reopen since we don't get the time to test and comment.

**Comment by gravitylow** [comment]
Hopefully that fixes it for good ^ http://ci.h31ix.net/job/AntiCheat/139/

**Comment by Rojoss** [comment]
Nope it's even worse now :S
Instant jail for breaking 1 log

18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] [ALERT] This means they probably are hacking or are lagging out!
18:46:20 [SEVERE] [AntiCheat] [ALERT] DR_EviL_1 has entered the HIGH hack level.
18:46:20 [INFO] Player DR_EviL_1 jailed for 4 minutes 59 seconds.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.
18:46:20 [SEVERE] [AntiCheat] DR_EviL_1 tried to break a block of LEAVES that was too far away.

**Comment by gravitylow** [comment]
Just noticed that before you commented :D fixed http://ci.h31ix.net/job/AntiCheat/140/
