### ISSUE TITLE
I'm op and I can't even fastplace!

### ISSUE THREAD

**Issue by cuddylier** [gravitylow/AntiCheat#100]
I'll keep this short and sweet. Basically this came up http://gyazo.com/0153b95868943ba2b3b0b23174183984.png?1340280563 and I'm op. I am using DEV-b219

**Comment by SuperSpyTX** [comment]
Ops are not exempt to the checks.  You will need to add those yourself.

@h31ix you can check this in plugins.yml if you wish.
