### ISSUE TITLE
Ender pearls

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#103]
Players using ender pearls are getting "tried to fire projectiles too fast"

**Comment by SuperSpyTX** [comment]
Wrong issue tracker.

File at http://dev.bukkit.org/server-mods/anticheat/tickets

**Comment by ghost** [comment]
Oh sorry, in that case please update the link in your bukkit page. At the bottom it says:

Please make bug reports by hitting the [tickets button at the top of the page](https://github.com/h31ix/AntiCheat/issues). If you leave an issue on the comments, we will ask you to use this system instead
