### ISSUE TITLE
AntiCheat entity check causing spam.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#105]
Using anticheat  #248, it seems that there is a bug where it continues to report lagging or hacked clients and doesn't stop, even if the player is offline. I had to download the latest version on dev bukkit so I don't see the spam. :(

**Comment by ghost** [comment]
Also seems to be an issue with entities when being thrown. For example, throwing snowballs spams the staff with error reports and not all snowballs are thrown.

**Comment by cuddylier** [comment]
i am experiencing this on latest dev as well.

**Comment by gravitylow** [comment]
Duplicate of cuddylier's issue and the one on our site, closing because it's resolved.

**Comment by ghost** [comment]
;-; Yet I posted it first. Alright then.
