### ISSUE TITLE
Recognizing "Stargate" port as fly hack

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#106]
I find a little issue when using "AntiCheat v1.3.3" with plugin "Stargate". That plugin can make any kind frame act like a portal and I find it great for a traveling around the world. When its used for a distance travel, there is no problem,... but when its used as an elevator, (just changing player Y coordinates) and player run thru it, then AntiCheat gets activated and recognize it as a "Fly" hack and sometimes return player 1 block below his original Y coords, that means he's half burried in the ground,...and sometimes it push him much further in the ground,...

This problem actually don't happend if the player step thru the portal really slowly.... so it's not a big issue, I just thought you might want to know about it,....

**Comment by gravitylow** [comment]
http://bugs.h31ix.net
