### ISSUE TITLE
Wall Climb not getting blocked

### ISSUE THREAD

**Issue by thekeenant** [gravitylow/AntiCheat#11]
While testing by myself, I discovered that wallclimb was not getting detected by anticheat. The client I used to test it with is called "Platinum Client" (a quick Google search will find it). Latest dev build of AntiCheat

**Comment by thekeenant** [comment]
Any updates

**Comment by thekeenant** [comment]
Didn't mean to close this issue.... Any updates on this problem?

**Comment by SuperSpyTX** [comment]
Could you test Nodus clients wall climb hack?

**Comment by SuperSpyTX** [comment]
I assume this was a permissions issue.  Invalid.

**Comment by thekeenant** [comment]
Yep... Oops
