### ISSUE TITLE
Anticheat reporting hacking/lagging even if player is offline.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#110]
http://pastebin.com/0Zkdmkr5

Anticheat reports if a player is hacking or lagging, which is a given, however, it continues to spam these warnings even if a player is offline. The only way to fix this issue is to restart the server.

Anticheat #249

**Comment by gravitylow** [comment]
http://bugs.h31ix.net

**Comment by ghost** [comment]
Yeah, thanks for giving me the link that I already tried. I've tried numerous times to post it but continues to say MySQL error. >_>

**Comment by gravitylow** [comment]
People have posted numerous errors over the last few days. It's working fine.

**Comment by ghost** [comment]
Well, if it was working fine, it wouldn't continue to spam hack reports/lag reports for offline players.

**Comment by gravitylow** [comment]
....?
The bugtracker is working fine.... That's what we've been discussing.

**Comment by ghost** [comment]
I just tried again, mysql error after trying to submit one.

**Comment by gravitylow** [comment]
I've added error reporting, try it again and if it says MySQL Error again let me know so I can take a look at the issue.
