### ISSUE TITLE
Creative fly issues

### ISSUE THREAD

**Issue by jamietech** [gravitylow/AntiCheat#114]
`[11:23.28] 18H31IX> I have a bug, why file a bug report? Just say it's buggy and move on.`
When flying with creative mode there are some issues when you disable flying to drop down a little and re-enable it to go up further. There are also issues in landing with creative mode flying as it teleports you under the block you land on O.O

And I don't know what versions were being used, you'd have to ask @mbaxter

**Comment by gravitylow** [comment]
Closed, we don't use this bugtracker.
