### ISSUE TITLE
Digging with Efficiency IV shovel results in MED/Kick

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#12]
Messages were:
[player] tried to break a block of SAND without swinging their arm.
(repeated 20 times in 3-4 seconds)
[player] has entered the MEDIUM hack level.
This means they may be using a hacked client or may have a bad connection!
[player] tried to break a block of SAND without swinging their arm.
(repeated 30 times in 5 seconds)
[AntiCheat] [player] was kicked for hacking.

**Comment by ZathrasNotTheOne** [comment]
I put [player] in place of the actual player name.

**Comment by ZathrasNotTheOne** [comment]
Seems to be true of high efficiency pick-axe on sandstone and probably other blocks as well.

**Comment by gravitylow** [comment]
Thanks, I'll be looking into this very shortly.

**Comment by gravitylow** [comment]
Fixed as of #128 http://ci.h31ix.net/job/AntiCheat/128/

**Comment by ZathrasNotTheOne** [comment]
Confirmed fixed.  Thanks.
