### ISSUE TITLE
AutoUpdater Bukkit version issue.

### ISSUE THREAD

**Issue by ST-DDT** [gravitylow/AntiCheat#123]
The AntiCheat AutoUpdater updated to latest AntiCheat version (which is compatible with Bukkit 1.4.6 i guess),
but it couldn't be enabled because we still use Bukkit 1.4.5.
This crushed almost all permissions on our server and we had to whitelist it 
because we couldn't find the cause at the beginning.
After a while we found the couldn't enable message and started asking our team. 
Did somebody change anything in AntiCheat? No? Strange...

There was no message, that AntiCheat has been updated at all.

Here is my request:
Please check first if the downloaded version is compatible with current bukkit version.

And add a message, that AntiCheat has been update.

**Comment by SuperSpyTX** [comment]
There's a configuration for a reason.

Set `Auto update: true` to `Auto update: false`
