### ISSUE TITLE
When someone is using iron shovel or better on dirt he gets blocked.

### ISSUE THREAD

**Issue by Kubuxu** [gravitylow/AntiCheat#126]
http://pastebin.com/ktFb6Xkc

We are just using iron or better shovels to mine dirt.

**Comment by gravitylow** [comment]
Please include a debug log. To do so, wait until after the issue occurs and then type /AntiCheat debug. Paste the resulting link here.

**Comment by Kubuxu** [comment]
@h31ix http://pastebin.com/qcTK7wH9

@SuperSpyTX ??

**Comment by gravitylow** [comment]
@SuperSpyTX chill out.... 
@Kubuxu thanks, I'll look into it once I'm back home,

**Comment by gravitylow** [comment]
It seems that after a while of digging (maybe 20 or 30 blocks) this starts to occur very rapidly, but before that point there are no warnings. Does that sound like what you're experiencing?

**Comment by Kubuxu** [comment]
Yes. That happens on our server.

**Comment by gravitylow** [comment]
Thanks, I'll look into the cause.

**Comment by gravitylow** [comment]
I believe to have fixed this in AntiCheat v1.4.3, try it out please.
