### ISSUE TITLE
Lag = kick?

### ISSUE THREAD

**Issue by doglover129** [gravitylow/AntiCheat#127]
I have a player on my server who lags quite a bit. It always kicks her. Is there a command that can whitelist a specific player? If not, can it be added?

**Comment by SuperSpyTX** [comment]
If your plugin allows, you can give specific permission nodes.

**Comment by gravitylow** [comment]
Use permissions for this purpose. There are pretty much no plugins that don't allow player-specific permissions, as long as I'm remembering correctly. As this seems to solve your question, I'm going to close this.
