### ISSUE TITLE
Add additional details on AntiCheat violations

### ISSUE THREAD

**Issue by SuperSpyTX** [gravitylow/AntiCheat#135]
Stuff like:
- Time it took to perform action (break/place blocks)
- Additional Information (Tool & Block to break)

This will be super-duper helpful when adjusting magic.yml values, and making better judgements on what values to lower.

I'll also make it a configuration option, so additional details can be hidden.

I'm thinking of logging it like this:
[AntiCheat] SuperSpyTX has tried to break a block of GRASS too fast - 73ms - DIAMOND_PICKAXE

**Comment by gravitylow** [comment]
Added this. Will continue to build upon it and add more information as things prove useful.
