### ISSUE TITLE
NoSwing triggered by breaking sugarcane

### ISSUE THREAD

**Issue by gramoobi** [gravitylow/AntiCheat#136]
When you break sugarcane you can line it up and beak like 3 at once in vanilla but anticheat i guess counts it as using noswing... also, when i use /anticheat spy it just teleports me to the player completely visible and everything

**Comment by SuperSpyTX** [comment]
Please provide /anticheat debug logs for further assistance.

**Comment by gramoobi** [comment]
So just type /anticheat debug anytime? or should i do it right after someone hacks or what?

**Comment by gramoobi** [comment]
http://pastebin.com/E6R5hmxB Thats from just typing that

**Comment by gramoobi** [comment]
also using shears on trees triggers fastbreak

**Comment by gramoobi** [comment]
Heres a new debug where i was testing the limits of the plugin...
http://pastebin.com/dnx0jg5G 
Fr0gb0y tried to break a block of OBSIDIAN too fast. That is breaking it with no hacks just efficiency III
gramoobi tried to break a block of LEAVES without swinging their arm. This ones using no hacks just plain shears

**Comment by gravitylow** [comment]
I'm getting fastbreak but no noswing issues. I'll look into it.

**Comment by ryantheleach** [comment]
i can confirm that shears on leaves causes no swings + break too fast.
