### ISSUE TITLE
2 Bugs?!

### ISSUE THREAD

**Issue by TheVnChecker** [gravitylow/AntiCheat#137]
Hey AntiCheat-developer.

I have 2 issues for you.

The first bug ist the "Waterwalk check". It teleport all swimming player to the last place where they stay before they jump in the water to swim.

The second bug (or not) is the "Fastinventory check". It kill the player when they sort the inventory with the Mod "InvTweak" but i think this plugin only warn/kick and ban player? So why it kill players?

**Comment by TheVnChecker** [comment]
[Edit] I've found a new issue. When Player dig with a stone shovel, then they get warn and kick from the plugin. But the Server doesn't lag or have other problem. So maybe you can fix this too please.

**Comment by gravitylow** [comment]
It'd be great if you could file these individually so we can keep track of them. I also need debug logs. /anticheat debug

**Comment by TnTBass** [comment]
I'm ok with them killing players who use InvTweaks.  I've been seeing that myself.

Waterwalking check may need some magic.yml tweaking.

**Comment by gravitylow** [comment]
I also agree with the whole inv tweaks thing; I'm not going to consider that a valid bug as I don't have any intention of supporting mods that change inventory behaviour.

**Comment by gravitylow** [comment]
I'll need a debug log or else I'll be forced to close this report.
