### ISSUE TITLE
mcMMO does NOT work out of the box.

### ISSUE THREAD

**Issue by CerealKlla** [gravitylow/AntiCheat#138]
I'm running a server and would like to make use of AntiCheat, however despite advertising that it works out of box with mcMMO, users  are getting kicked and reported as hacking for using ANY right+click mcMMO ability. I've confirmed this with every tool (pick, shovel, and axe) I've also tried manually changing the magic file to make it more lenient, but your documentation doesn't really help determining which are contributing to this issue, and regardless don't seem to effect anything when changed. (Yes i'm reloading the server)

**Comment by CerealKlla** [comment]
Hello? is anyone actually working on this plugin? I've had to disable it because people can't enjoy the server, is there any fix in store? i'm using the dev version of bukkit, mcmmo, AND anticheat if that helps you out.

**Comment by gravitylow** [comment]
Chill out bud, even though I haven't replied I saw your issue just as I have with every issue on here. Please be patient and respectful as I actually work on this plugin.

You haven't included a debug log AFTER the issue occurs (/anticheat debug), though, which doesn't make the job simple. Please do so if you want to get this looked at soon :)

**Comment by CerealKlla** [comment]
Not trying to be rude, just making sure someone saw it; it wasn't flagged as in progress or anything so i figured it wasn't seen is all.

**Comment by gravitylow** [comment]
I've tagged it, please get back to me with those reports and I'll have able to work on it.

**Comment by CerealKlla** [comment]
Should i know what reports you're referring to? All the tag says is, "Needs more info" ...

**Comment by gravitylow** [comment]
Did you see my comment above? I told you how to provide an AntiCheat debug log.

**Comment by gravitylow** [comment]
Fixed https://github.com/h31ix/AntiCheat/commit/8c82571b8681d1d4a8c9496086ff128d4fe412d4
