### ISSUE TITLE
Anticheat fastbreak false positives

### ISSUE THREAD

**Issue by OdiumxXx** [gravitylow/AntiCheat#139]
constantly there are false positives for fastbreak
if you use anything above your fists to break a block, it triggers.
it's impossible to stop using anything other than the permission to no longer check for fastbreaking.

http://pastebin.com/CzRqXvdh

**Comment by gravitylow** [comment]
Try the latest dev and report back, please.

**Comment by ryantheleach** [comment]
on #398 dev build. http://pastebin.com/0eKXPDD8 don't know if it helps any.

**Comment by ryantheleach** [comment]
Just tried #399 has fixed it for carrots, _may_ have fixed enchanted tools mining stuff as well, but needs more testing.

**Comment by gravitylow** [comment]
Please do so and report back.

**Comment by ryantheleach** [comment]
fixed it at least for vanilla clients with little to no lag.

**Comment by Trikolon** [comment]
Build #400 fixed these issues for me.

**Comment by gravitylow** [comment]
Good stuff. Let me know if there's anything else.
