### ISSUE TITLE
"tried to alter their timer."

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#140]
http://pastebin.com/2A4rmWyw
Honestly, I hate that there is no real match with checks name in-game and magic.yml
That's probally means alot when you trying to configure AntiCheat as you want. 
The issue is about matching check names at magic.yml and in-game. I can't find info wich exactly check player has failed. But info about how do I fix "tried to alter their timer" is fine too.

**Comment by columb** [comment]
For example: Open http://gravitydevelopment.net/docs/anticheat/net/h31ix/anticheat/util/Magic.html Hit ctrl+f and type "timer". 0/0. "Speed"? Almost 60!

**Comment by gravitylow** [comment]
You need to be using the latest version. 1.5.1 is old.

**Comment by columb** [comment]
@h31ix Have you added correct check names into latest version? If no, re-open the issue then. I don't like idea of AntiCheat plugin without even possible way to configure it. Configurin is fine. But damn, there should be more info about wich cheks (wich match check names in magic.yml) player has failed.

**Comment by gravitylow** [comment]
F5 the page. In any case, the timer check is still under testing so there's no reason to worry about it being there or not. It's there, though.
