### ISSUE TITLE
More actions on violation level

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#141]
Why player goes to "medium" level I would like to clean-up his inventory (one of the commandbook commands, /clear -a <username>) and warp him (/warp <player> hackingisbad) into place where he got info about why he shouldn't continie hacking. As for now there is only 1 command per  violation level (there is only 2: "medium" and "high").
 I love the idea how ServerSigns execute commands. You can perform a command as server console with following format: <server> <command> <player>. 
  For example, temp ban for 25 minutes gonna looks like this: "<server> ban -t 25m <player> STOP HACKING"

**Comment by gravitylow** [comment]
Would allowing something like COMMAND[/command 1;/command 2] work if implemented?

**Comment by columb** [comment]
With support for for %player% variable? Yeah, guess so. A bit better to separete it into lines other than writte everything in one.

**Comment by gravitylow** [comment]
There's support for &player which wouldn't go away if I implement this.
