### ISSUE TITLE
Riding on a Pig will detect you as Flyhacker

### ISSUE THREAD

**Issue by Petschko** [gravitylow/AntiCheat#143]
http://www.eona.in/images/upload/2013-01-12_15.06.29.png

Hello,

when you ride on a Pig anticheat will detect you as a Flyhacker. This bug is repeatable. See the picture on the top! You can redo this evertime on your server! After ~5 Minutes you get detected!

Sorry for my bad lang =/

Thank you for listening!

Petschko

**Comment by Trikolon** [comment]
I also experienced this. You can provide a log with /anticheat debug   to make it is easier for them to fix the issue.

**Comment by gravitylow** [comment]
The pig riding seems to work fine for me..

**Comment by Trikolon** [comment]
Did you also boost your pig by doing rightclick with the rod?

**Comment by gravitylow** [comment]
Mhm. It's looking normal to me :/

**Comment by Petschko** [comment]
Here I do the debug:

http://pastebin.com/BWtfgvfX

Yes I try to ride a pig, while boost it and i try to ride it without rightclicking the rod. I was kicked in in this two cases.

I excuse my bad english again. =/ Thank you!

**Comment by gravitylow** [comment]
I've tested this on 3 different servers and have been unable to reproduce the problem. If you have a video maybe? I just can't it to work (or not work, depending on how you look at it) at all.

**Comment by Petschko** [comment]
Sure, you can watch it here: http://www.youtube.com/watch?v=1r6tanmVYMY

Content:
1. Entering the Server
2. Get on the Pig
3. Ride
4. Get warned
5. Get kicked

**Comment by gravitylow** [comment]
It looks like riding up the stairs is the mostly causing the issue, is that right?

**Comment by Petschko** [comment]
No, other Players on the Server get also kicked, when they ride on a pig and I think, they not ride on the Serverways. Many people have their home not on the street. I have test it again on a flat plain and i was also kicked.

**Comment by gravitylow** [comment]
Are you saying this bug is only happening to you on your server?

**Comment by Trikolon** [comment]
I also have issues with it. Does it have to do anything with the players height, or is that the same as when walking ?

**Comment by gravitylow** [comment]
The height doesn't really matter, height only relates to an entity's height which is assigned at creation and is static from there on; if anything this would be an issue of location.

**Comment by gravitylow** [comment]
This is truly bizarre. Under no circumstances have I been able to reproduce this, even after watching the video. You both have tried this on the very latest dev build and had the same result, is that right? This one? http://ci.h31ix.net/job/AntiCheat/406/

**Comment by Petschko** [comment]
Ive used the newest one on this page: http://dev.bukkit.org/server-mods/anticheat/files/ (v1.5.3) I can test it again, with your file (created on January 16th)

Edit:
I can't redo the issue with this version: http://ci.h31ix.net/job/AntiCheat/406/

**Comment by gravitylow** [comment]
Okay. The next update will contain the fix, then. It must just be an issue with the last one. Thanks!
