### ISSUE TITLE
Y axis fly false positive.

### ISSUE THREAD

**Issue by ryantheleach** [gravitylow/AntiCheat#144]
2013-01-13 23:40:43 [INFO] Templer117 tried to fly on y-axis

Happens when user holds w and walks up stair blocks.

**Comment by gravitylow** [comment]
I wasn't able to reproduce the issue. Could you please send me a debug log (/anticheat debug) and possible a screenshot of the stairs where it is occurring? Just so I can get an idea of the setup.

**Comment by ryantheleach** [comment]
http://pastebin.com/E3Z9cB3K
http://screensnapr.com/v/mvKSwW.jpg
http://imgur.com/xi6rx
also seems to trigger speed on downhill, fly on uphill

standing at bottom of stairs, looking up, is F:1 west.

**Comment by gravitylow** [comment]
Hm. While that's good info, I still can't get it to occur on the same setup.
Can I ask you to please try the latest dev and see if the issue is still occurring there?
If so, it'd be great to get a debug log from that to have more info on the situation.

**Comment by ryantheleach** [comment]
where can i get the latest dev build from, is it possible to switch to dev builds using your updater script?

**Comment by gravitylow** [comment]
http://ci.h31ix.net

**Comment by gravitylow** [comment]
Any update on this?

**Comment by ryantheleach** [comment]
The player that could recreate it hasn't been online lately

**Comment by gravitylow** [comment]
If you can't actually reproduce it yourself, it's almost certain I'm not going to be able to.
