### ISSUE TITLE
AntiCheat is way to sensitive.

### ISSUE THREAD

**Issue by DiscoCat42** [gravitylow/AntiCheat#145]
Iv'e been working with AntiCheat for a while, and have always had some sort of problem with it. Riding pigs makes AntiCheat go nuts, saying user is fly hacking. If they break farm blocks, such as sugar cane, potato's, carrot's, etc, it tries to get them for fastplacing/fastbreaking/noswing. Is there anyway to make AntiCheat not so sensitive? I'd use NCP. but quite frankly, I don't like it. Its not as organized. But iv'e been poking around the folder and iv'e messed with the config. That didn't really do much. Iv'e looking into the magic file, one look at that made me wanna quit AntiCheat, I had no idea what to do with that. And it always seems to nail the people that aren't hacking. the hackers can get away with flying, speedhacking, etc. But the people that aren't get slammed by AntiCheat. I'm just looking for a fix to this, because I really enjoy this plugin. Thanks.

**Comment by Trikolon** [comment]
Thats also how my players feel at the moment.  The plugin is really good, it just seems to be very strict with players lagging a bit.

**Comment by gravitylow** [comment]
I understand this sentiment completely. It's a tedious balance between too restrictive, thus pissing people off, and too lenient, thus pissing people off. It's pretty hard to fit right into that, and NoCheat was able to do it only after a long time of operating. NoCheatPlus got the upper hand by taking that work and just expanding upon it. 

What I would suggest you do is download the latest dev build which includes much more detailed logging that will help you with magic.yml configuration. I didn't design the file to be user-simple, unfortunately, just an editable key-value store. Sometime soon when I have more time I'll keep working on the configurator for the file, but for now you'll just be able to see what people are setting off and why, and adjust values to fit your server. Once you've done that, it'd be great to push those improvements back upstream by suggesting changes to default values.

I'm only one guy, and while I do have a lot of people helping tremendously with testing, I don't even run a server myself (again, not enough time) and so it's hard for me to do ALL of this.

**Comment by Trikolon** [comment]
Thank you for your help. I will try the latest dev-builds.

**Comment by gravitylow** [comment]
I've fixed some of the problems you mentioned. Since this isn't really a valid bug I can say is 'fixed', I'm going to go ahead and close it. If there's not already a ticket open for a specific item you mentioned, feel free to make one.
