### ISSUE TITLE
Match check names from /anticheat debug to magic.yml

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#147]
http://pastebin.com/LD3teRkB
http://gravitydevelopment.net/docs/anticheat/net/h31ix/anticheat/util/Magic.html
Yet again I can't ctrl+f "ascend" check

If I have to deal with bans of innocent peoples due to AntiCheat fails or my misconfiguration I would like to be able to configure some checks as I want. But since there is no easy way to debug it by myself...

**Comment by gravitylow** [comment]
Use the latest dev please.

**Comment by columb** [comment]
@h31ix 
Thanks, much better. (:
