### ISSUE TITLE
Fast break false positive

### ISSUE THREAD

**Issue by ryantheleach** [gravitylow/AntiCheat#149]
http://pastebin.com/DfuHvgyi

efficiency 3 pick on netherrack, pretty much the fastest (that i know of) combination in the game.

**Comment by gravitylow** [comment]
Please use the latest dev build and report back.

**Comment by ryantheleach** [comment]
oh, you work FAST. updating now, also, http://pastebin.com/u3RGmQ9L it gets reports for planting seeds as well.

**Comment by gravitylow** [comment]
It was already fixed :> just on a dev build you didn't have.
If you update let me know if it fixes your second problem too or not.

**Comment by ryantheleach** [comment]
yeah, sorry, ill make doubly sure to update as soon as someone says they have issues, didnt realize you had daily updates out, most devs seem to do bigger amounts less often,

Seeds where fixed until it lagged when someone joined, http://pastebin.com/GnT2G24d but im assuming you cant help that.
 Whats with the 0 times in a row?

anyway keep up the good work!

**Comment by ryantheleach** [comment]
Also, does block hardness work on cobweb? players have reported that swording cobwebs make them "hack"
http://www.minecraftwiki.net/wiki/Digging has a whole section on tools and digging speeds.

things you may not have accounted for: shears on cobweb, wool. anything gets accelerated using a sword vs fists, underwater block slowdown.

**Comment by gravitylow** [comment]
There are tests that ensure all block hardnesses are accounted for on each update.

**Comment by ryantheleach** [comment]
its got to do with specific tools tho, and multipliers on top of them.

**Comment by gravitylow** [comment]
Yes, I'm well aware, and can assure you that it is compensated. See utils/BlockHardness and utils/ToolHardness. Now, if there's a specific reproducible issue you're having, feel free to make a ticket for it, but I can assure you that what you're asking about is indeed included in the math.

**Comment by ryantheleach** [comment]
I looked over the code before linking the relevent wiki section, and I have double checked again, and I can not find where cobwebs breaking faster with a sword is accounted for. http://pastebin.com/VrjRyKrJ

**Comment by gravitylow** [comment]
I haven't been able to duplicate any fastbreak when using a diamond sword on web in the latest dev.

**Comment by ryantheleach** [comment]
I hate to nag, but where is this covered in the code? It's been bugging me that I can't find it.

**Comment by gravitylow** [comment]
I don't think there's a specific case for it; there usually doesn't need to be unless the result of the Material + Item = a break time of way less than expected (e.g. sheers and leaves). From my testing, breaking webs with swords works fine, which means the math calculating diamond items on cobwebs works fine by itself.

**Comment by ryantheleach** [comment]
are you testing locally? the difference between a real connection and a lan/local may be enough to tip it over.

**Comment by gravitylow** [comment]
Nope.
