### ISSUE TITLE
Using /spawn causes y-axis fly warnings

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#15]
Using build 129.  A player issues /spawn and AC generates a warning on console:
[WARNING] [AC] xxxxxxx tried to fly on y-axis

The player was prevented and received a message that said he had fly mod.

He tried it 4 times and it issued over a dozen total warnings.

If it matters, my spawn has a lower elevation that ground level.

**Comment by SuperSpyTX** [comment]
This is part of issue #9,  but ill leave it open.

**Comment by gravitylow** [comment]
Fixed in http://ci.h31ix.net/job/AntiCheat/131/, please re-open if you discover any issues with this that you did not mention earlier.
