### ISSUE TITLE
fall damage false positive

### ISSUE THREAD

**Issue by ryantheleach** [gravitylow/AntiCheat#150]
[AntiCheat] ryan_the_leach tried to avoid fall damage (fall distance = 0 1 times in a row, max=+9)

im getting these a few times, they are extremely hard to recreate, however ive managed to do it while running over a chest glowstone chest glowstone pattern.

It would be good to have a sanity check, to make sure that the fall damage being avoided would  be > 0 before damaging the player, as it causes half heart damage.

**Comment by gravitylow** [comment]
It's harmless. Just a reporting bug.
The number checked gets reset before the report goes through, meaning that when the report displays the number it's showing it's reset value (0).
The check wouldn't have failed unless the max was indeed > 9

It'll be fixed.

**Comment by gravitylow** [comment]
Should be fixed in latest dev, reopen if not.
