### ISSUE TITLE
Add a freecam check [Line of sight]

### ISSUE THREAD

**Issue by timbru31** [gravitylow/AntiCheat#152]
Hey there,

first of all, AntiCheat is great and blocks many Nodus/hack features! :+1: 

However, freecaming is still possible and players can fly through walls and open chests behind them.
I found a plugin which prevents this but believe such a feature should/could be implemented into AntiCheat, too!

Basically it's a check when the player opens a chest/furnace/workbench etc [InteractEvent] if the player can see the block or not.

Resources:

Plugin I found to prevent this: http://dev.bukkit.org/server-mods/chestfix/
Source code: https://github.com/netherfoam/ChestFix
Demonstration (lower your volume!): http://www.youtube.com/watch?v=2Ci-FKQzJGs

If you believe you don't want to implement this, it's okay too, just close this issue then ;)

Cheers,

**Comment by Trikolon** [comment]
I suggested that in the past, he wants to include that I think. :)
Would be also useful for pvp-arenas.

**Comment by columb** [comment]
Oh yea! And buttons too!

**Comment by gravitylow** [comment]
The code's there to check it, it just isn't added on the event. I'll look into making this work well.

**Comment by timbru31** [comment]
Sounds good :)

**Comment by gravitylow** [comment]
Added to the version 2.0 milestone.
