### ISSUE TITLE
Possible crash cause and errors

### ISSUE THREAD

**Issue by GaryQian** [gravitylow/AntiCheat#153]
My server is occasionally randomly freezing (crashing) with no errors on the crash itself. The console just freezes with no output and takes a restart to get back online. This is showing up in the console when I stop the server:

This is on Bukkit 1.4.6 r0.3 #2586

18.01 16:47:32 [Server] INFO Disabling VanishNoPacket v3.14.2
18.01 16:47:32 [Server] INFO Plugin disabled.
18.01 16:47:32 [Server] INFO Disabling IslandWorld v1.3.6
18.01 16:47:32 [Server] INFO [Factions v1.8.0] Disabled
18.01 16:47:31 [Server] INFO Disabled link to plugin Factions, version 1.8.0
18.01 16:47:31 [Server] INFO Disabling Factions v1.8.0
18.01 16:47:31 [Server] WARNING at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
18.01 16:47:31 [Server] WARNING at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:458)
18.01 16:47:31 [Server] WARNING at net.minecraft.server.v1_4_6.MinecraftServer.stop(MinecraftServer.java:351)
18.01 16:47:31 [Server] WARNING at org.bukkit.craftbukkit.v1_4_6.CraftServer.disablePlugins(CraftServer.java:277)
18.01 16:47:31 [Server] WARNING at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
18.01 16:47:31 [Server] WARNING at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
18.01 16:47:31 [Server] WARNING at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
18.01 16:47:31 [Server] WARNING at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
18.01 16:47:31 [Server] WARNING at net.h31ix.anticheat.Anticheat.onDisable(Anticheat.java:95)
18.01 16:47:31 [Server] WARNING at net.h31ix.anticheat.util.Configuration.saveLevels(Configuration.java:295)
18.01 16:47:31 [Server] WARNING at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:54)
18.01 16:47:31 [Server] WARNING at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:233)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:207)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:180)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:215)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:637)
18.01 16:47:31 [Server] WARNING at org.yaml.snakeyaml.emitter.Emitter.writeIndicator(Emitter.java:1088)
18.01 16:47:31 [Server] WARNING at java.io.StringWriter.write(Unknown Source)
18.01 16:47:31 [Server] WARNING What follows is the stack trace of the main thread
18.01 16:47:31 [Server] WARNING Probable Plugin cause: 'AntiCheat'
18.01 16:47:31 [Server] WARNING The main thread failed to respond after 10 seconds
18.01 16:47:31 [Server] INFO Disabling AntiCheat v1.5.3
18.01 16:47:31 [Server] INFO Stopping server
18.01 16:47:31 [Server] INFO CONSOLE: Stopping the server..
18.01 16:47:31 [Server] INFO CONSOLE: Save complete.
18.01 16:47:31 [Server] INFO CONSOLE: Forcing save..
18.01 16:47:31 [Disconnect] User JustSteve has disconnected, reason: disconnect.endOfStream
18.01 16:47:31 [Disconnect] User Riptide has disc

**Comment by gravitylow** [comment]
Looks to me like your /data/level.yml file is messed up. Have you tried resetting it?

**Comment by gravitylow** [comment]
Any update on this?

**Comment by gravitylow** [comment]
Closing. Let me know if you see anything otherwise.
