### ISSUE TITLE
Nuke

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#157]
On spleef players are able to destroy ~10 blocks in 1 second. Possible limitation for amount of blocks wich player can interact in 1 second?

**Comment by gravitylow** [comment]
Please provide a debug log and additional information.

**Comment by columb** [comment]
@h31ix wich check should be triggered when players tries to interact with too many things at once? I've done /anticheat report to  player with nuke, but he doesn't have any violation related to it.

**Comment by gravitylow** [comment]
It's fastbreak.

**Comment by columb** [comment]
Issue could be closed, spleef developer added anti-nuke in the latest build.
