### ISSUE TITLE
AC prevents y-axis change when using a MultiVerse portal 

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#16]
AC Build 129.

When a player uses a multiverse portal, it logs a warning:

[WARNING] [AC] xxxxxxx tried to fly on y-axis

MV changes their x and z positions, but their y position stays the same and they end up above or below the actual portal, often resulting in player death.

Multiverse-Core 2.4-b525
Multiverse-Portals 2.4-b540
CraftBukkit build 2149

**Comment by ImShady** [comment]
I second this, but this happens when doing /spawn in my case or /f home (factions)

**Comment by SuperSpyTX** [comment]
I'll need more details for this to be confirmed.

Multiverse Portals work completely fine for me.

**Comment by gravitylow** [comment]
Is this also fixed in http://ci.h31ix.net/job/AntiCheat/131/? (Seems it is. closing)

**Comment by ZathrasNotTheOne** [comment]
So far, yes.  Looks good.
