### ISSUE TITLE
Fastbreak false warning when using enchanted pick

### ISSUE THREAD

**Issue by Jamer99** [gravitylow/AntiCheat#160]
I'm not a admin on the server or deal with the warnings but it seems that if you have eff3 or higher on a dpick it triggers fastbreak warnings

**Comment by ryantheleach** [comment]
Ask the owner of the server to update to the latest DEV build and see if the problem persists, an update several days ago fixed this for me.

**Comment by gravitylow** [comment]
Any update on this?

**Comment by gravitylow** [comment]
Closing.
