### ISSUE TITLE
Never reset HIGH group.

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#162]
I would like to be able to read reports about players with HIGH level even if they are banned long time ago. In case that players are keep asking for unban and I can't be sure which hacks did they used, since it's just could be my misconfig/anticheat bug.
 Could you also expand anticheat debug info from 30 to 50?

**Comment by gravitylow** [comment]
The hacks they use is only kept in memory; only their level is stored to disk. If you have tons of people asking for unbans, you should stop letting AntiCheat handle banning and investigate yourself. That's all AntiCheat is there to do, and is a reason why AntiCheat doesn't ban ANYONE by default.

**Comment by columb** [comment]
It's okay to ban cheaters, I don't really care about them and there are too many of them at pirate server. Yaarr. Could you add option to move info about used hacks from memory to disc when they get medium level?
Also I doesn't like idea of just blocking hackers. They must be banned. Like VAC or UAC do. Since as for now anticheat doesn't block all hacks completly. They still able to get advantage with even when server trying to prevent it.
