### ISSUE TITLE
Permission to bypass moving from low to medium group.

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#163]
I would like to prevent trusted players getting kicked/banned for hacks but anticheat should stay trying to block hack using for them.

**Comment by gravitylow** [comment]
Use permissions. Please read the documentation before creating reports. http://dev.bukkit.org/server-mods/anticheat/pages/permissions/

**Comment by columb** [comment]
You probaly don't get my idea. I wouldn't disable checks for my "trusted" players. Their tries to hack should be rollbacked to prevent abuse. But they shouldn't get any other punishment like kick or ban (Moving into medium/high group).
