### ISSUE TITLE
Quit message

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#164]
Hide "left the game" since AntiCheat prints custom quit message? Two at once looks kinda weird.

**Comment by gravitylow** [comment]
Closed.. AntiCheat doesn't print custom quit messages...

**Comment by columb** [comment]
Quit = kick for anticheat violation and it's probally custom quit message since it's displays to everyone in chat with name and reason for quit.

**Comment by Trikolon** [comment]
This feature is absolutely not needed. If you ban someone with bukkit it also says "player left the game". This information is useful and does not need to be blocked.

**Comment by columb** [comment]
It's DOULE message. I've got 1 informative message why player leaves the games from anticheat and another one pretty useless with "left the game" from craftbukkit.

**Comment by Trikolon** [comment]
This is no way important for this plugin. If you dont like the leave-message from bukkit and how they handle players connecting and disconnecting, contact them.

**Comment by gravitylow** [comment]
Anticheat uses the player.kick method. Any changes through that are unrelated to this plugin.
