### ISSUE TITLE
Allow to add more violation groups via config

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#165]
I would like to add 1 more violation group, just to be sure that player is uderstanding that he gonna get banned for using hacks. I would like to just add few lines into Events section in config.yml to Like "Lastchanse: KICK" and "Lastchanse theeshold: 10"

**Comment by gravitylow** [comment]
I'll probably revamp this system soon.

**Comment by gravitylow** [comment]
Pushed a new event system.
