### ISSUE TITLE
Disable anticheat cheks on server TPS drops.

### ISSUE THREAD

**Issue by columb** [gravitylow/AntiCheat#166]
Would be nice to autodisable AntiCheat checks (Or may be some of them) when server gets really overloaded, like 10 TPS (Or any other configurable amount) and autoenable it when it gets back to 18+.
 With this feature really large servers is gonna be able to use AntiCheat, since they sometimes doesn't have enough hardware resources (they want to allow their players play lag-free) avaible to allow some plugins handle the most perfomance unfriendly PlayerMoveEvent check and players isn't gonna get banned due to lag.

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat/issues/158#issuecomment-12517625
You realllyyy need to stop hanging on to this TPS stuff.

**Comment by columb** [comment]
@h31ix No you (:
#158

**Comment by Trikolon** [comment]
TPS is not really something to measure server-lag reliable. Just make sure your server does not have any lags, then you also do not have to worry about false-positives from AntiCheat because of that.

**Comment by columb** [comment]
@Tallcraft I have to deal with overloaded server with online  100+ players. Just click #158 for more info.
