### ISSUE TITLE
Spider Web "Fast Breaking"

### ISSUE THREAD

**Issue by kthyer** [gravitylow/AntiCheat#168]
When breaking spider webs with a sword you will get the message that says something like " FastBreak detected please wait 10 seconds before breaking anything else". Basically, it just prevents you from breaking any other blocks because it thinks you're using fastbreak since spiderwebs break very quickly when using the correct tool.

I'm using v1.5.5

**Comment by gravitylow** [comment]
Debug logs, please. /anticheat debug.

**Comment by Darkhand81** [comment]
I'm having the same problem, almost all users are setting off FastBreak when they use swords on webs.

Debug logs don't show much yet (http://pastebin.com/MUw6zwJ1), I rebooted a few times since I found out about the issue, but I'm sure I'll have fresh debug info later on tonight

**Comment by gravitylow** [comment]
In order to get a proper idea of the situation I need the debug log to be generated after the issue has occurred and before a reload. If you reload/restart it the logs are cleared. On your report there are no logs, which orang help me understand why the issue is occurring.

**Comment by Darkhand81** [comment]
New debug log, I simply placed a line of webs and started breaking them with a diamond sword.  'Fastbreaking detected' within 4 or 5 blocks, went to medium level after a dozen or so:

http://pastebin.com/K5y5s83t

**Comment by Darkhand81** [comment]
Having the same problem consistently with wool and shears also.  This is a continuation of the last log with wool/shear trouble after the old entries:

http://pastebin.com/nNEHVxnQ

**Comment by galqawala** [comment]
I have the same problem. We went to a cave spider nest with friends today. Me and a friend got that 10 second penalty for breaking cobwebs with iron swords. Is it related to lag? Sometimes when you break something it will reappear for a while. When will this be fixed? It is quite annoying. I couldn't find any workaround from the config file. 

[INFO|2:19:00]: tubelius broke blocks too fast 3 times in a row (max=2) 
[INFO|2:19:01]: tubelius broke blocks too fast 3 times in a row (max=2) 
[INFO|2:19:02]: tubelius broke blocks too fast 3 times in a row (max=2) 
[INFO|2:19:11]: tubelius broke blocks too fast 3 times in a row (max=2) 
[INFO|2:19:13]: tubelius broke blocks too fast 3 times in a row (max=2) 
[INFO|2:19:13]: tubelius broke blocks too fast 3 times in a row (max=2) 
[INFO|2:19:19]: kunai101x tried to break 2 blocks in 796 ms (max=2 in 1150 ms) 
[INFO|2:19:30]: tubelius tried to break 2 blocks in 953 ms (max=2 in 1150 ms)

**Comment by gravitylow** [comment]
I can indeed confirm this. Looking into it.
