### ISSUE TITLE
AntiCheat not working with BouncyBeds

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#17]
Nocheat works with it, but AntiCheat won't let them bounce.

Here is the plugin: http://dev.bukkit.org/server-mods/bouncy-beds/

I use version 1.1 as of now, and normal players cannot bounce on beds with AntiCheat on, however they could when we used NoCheat.

**Comment by SuperSpyTX** [comment]
Can you try using bouncy beds with the latest devbuild of AntiCheat?

**Comment by SuperSpyTX** [comment]
You can grab a devbuild at http://ci.h31ix.net

**Comment by Murabitos** [comment]
ok will do it soon and get back to you when i've tested it. is it safe to leave the dev build on there or should i switch back after testing?

**Comment by SuperSpyTX** [comment]
Your choice, But i'd recommend staying on devbuild.

**Comment by SuperSpyTX** [comment]
It appears this has to do with velocity, which can potentially effect players playing with plugins that mess with velocity.  This is going to be a problem since there is a few issues related to velocity which I won't discuss here.

**Comment by SuperSpyTX** [comment]
After discussing with h31ix, i'm asking that you nag the author of the plugin to use our API to make it compatible; it's very easy to implement and will allow your plugin and AntiCheat to work seamlessly together. Simply link the developer to this page and ask him to implement it: http://dev.bukkit.org/server-mods/anticheat/pages/api-documentation/
