### ISSUE TITLE
Pasing ban reason to command event

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#170]
As requested by Zero_Gravity I am filing this ticket

I am using your "COMMAND" event when banning as I use a non-default banning system and it works great but I was wondering if there was a way to pass the reason for why anticheat banned/kicked the player.

i.e. COMMAND[ban &player hacking, &reason] so a ban may look like "ban player hacking, fly"

Thanks!

**Comment by gravitylow** [comment]
Working on this in the new update (just to update you), it's going to assign "&check" the name of the check.

**Comment by gravitylow** [comment]
Added in the newest dev https://github.com/h31ix/AntiCheat/commit/52a90b9bc8d36f2588e3403048a633a5adef764a#L4R113
