### ISSUE TITLE
False y speed alert on boat exit

### ISSUE THREAD

**Issue by ryantheleach** [gravitylow/AntiCheat#172]
Especially if the boat breaks.

Whats the annoying part isn't the false report however but you are teleported to when the boat journey started.

**Comment by Trikolon** [comment]
I also experienced this.

**Comment by gravitylow** [comment]
Debug log, please.

**Comment by gravitylow** [comment]
I wasn't able to really get this working. Is this in shallow water.. or getting off on the shore or something? Boat breaking also hasn't caused the problem to occur.

**Comment by gravitylow** [comment]
Any update on this? Debug logs?

**Comment by gravitylow** [comment]
Going to close this, add debug logs please if you need it to be reopened.
