### ISSUE TITLE
Overly Sensitive Threshold

### ISSUE THREAD

**Issue by Xehara** [gravitylow/AntiCheat#173]
This plugin was installed yesterday (1/30/2013) and since then we have had many players kicked for false positives such as:
1. Sprinting too fast when going through a MultiVerse portal (happens sporadically, not every time)
2. mcMMO perks cause a violation response
3. Fast break message when breaking spider webs with swords
4. People being kicked for falling down mine shafts that have water at the bottom, as opposed to them using the ladders
   etc.

How do I go about correcting these issues on my end, or am I even able to?

**Comment by gravitylow** [comment]
You can edit the magic.yml values to fit your server.

Your first 3 issues all have tickets open and are being fixed. I haven't heard the last one, but if it's an actual bug I need to have a ticket created specifically for it with proper debug information so I can recreate the issue and fix it.

Closing this for now.
