### ISSUE TITLE
Nodus: Highjump, Nofall, Fly

### ISSUE THREAD

**Issue by DeadIntermediate** [gravitylow/AntiCheat#178]
Anticheat is no blocking these at all. Players are able to bypass this easily. Could you make update the plugin to make sure the plugin blocks these please? This is with the current version of Anti-Cheat 1.5.5

**Comment by Trikolon** [comment]
A debug-file would be helpful I guess. /anticheat debug

**Comment by gravitylow** [comment]
This seems very wrong. The video you see posted on youtube and on BukkitDev was filmed on this version of AntiCheat.

**Comment by gravitylow** [comment]
Debug logs?
