### ISSUE TITLE
Speed II potions not working (possibly Speed I also)

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#18]
When you drink Speed potions you cannot run properly. Please fix!

**Comment by SuperSpyTX** [comment]
This could be a actual bug.  I'll mark this as confirmed until I'm proven wrong.

**Comment by Murabitos** [comment]
Could be? :P I have a server full of people complaining haha..

Gioboi.g.nfoservers.com - pvp/anarchy/grief

**Comment by Rojoss** [comment]
I third this.
Speed potions aren't working good.

**Comment by SuperSpyTX** [comment]
When you guys get the chance, test this devbuild http://ci.h31ix.net/job/AntiCheat/134/

Then report results back to me and see if this resolved issue or not.

**Comment by SuperSpyTX** [comment]
I am going to assume this was fixed.

**Comment by Rojoss** [comment]
Will test it once jenkins is back up.

**Comment by SuperSpyTX** [comment]
Because of Cloudflare, I've downloaded the devbuild directly from the CI.

Here you go http://www.mediafire.com/download.php?qwke8m4n554cubm

**Comment by SuperSpyTX** [comment]
Assumes this is now fixed.
