### ISSUE TITLE
'Hacking (sprint)' on returning to overworld from end

### ISSUE THREAD

**Issue by thomasw96** [gravitylow/AntiCheat#180]
If a player returns from the end to the overworld, by a portal spawned by slaining an Enderdragon, the player stucks in the overworld and gets kicked because the player failed the Sprint check.
Even if a player moves (by looking and walking), the plugin says the player is hacking (Sprint).

**Comment by gravitylow** [comment]
Debug logs (/anticheat debug) of the false-positive occurring, please.

**Comment by thomasw96** [comment]
After a day the problem didn't occur again. People don't get kicked anymore if they return to the overworld.
In my opinion this issue is solved.
