### ISSUE TITLE
Freecam, waterwalk, forcefeild, clickaimbot.

### ISSUE THREAD

**Issue by XxGIRRxX** [gravitylow/AntiCheat#181]
These mods, stated above are still working in my server. I gave no permssions but the ones for my admin group and leadmod which gets xray, and spy.

**Comment by gravitylow** [comment]
Freecam is client-side and can't be fixed apart from what is already done. As for the others I'll look into it, could you please read the readme and give me the proper information I need to help you? https://github.com/h31ix/AntiCheat

**Comment by Darkhand81** [comment]
Does anticheat implement anything similar to ChestFix (http://dev.bukkit.org/server-mods/chestfix/) to combat freecamming? Just wondering if I need to run both or if AC has that covered. :)

**Comment by gravitylow** [comment]
I believe that should be blocked, feel free to test.

EDIT: Appears it isn't as long as the person is in range of the block. I'll see what I can do.

**Comment by gravitylow** [comment]
Fixed waterwalk.

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
