### ISSUE TITLE
NoSwing Error

### ISSUE THREAD

**Issue by jojodmo2010** [gravitylow/AntiCheat#182]
My players are constantly getting kicked and banned for No Swing in the PvP when they are not using noswing, I would like this error to be fixed or be able to turn off noswing

**Comment by gravitylow** [comment]
Please read the [FAQ](http://dev.bukkit.org/server-mods/anticheat/pages/q-a/) page to turn it off, and please provide me with a debug log, [read the readme](https://github.com/h31ix/AntiCheat)

**Comment by gravitylow** [comment]
Any debug logs or updates on this?

**Comment by StarfireHunter** [comment]
I am also having this problem, http://pastebin.com/2zhEB5bj This is my bug report.

**Comment by gravitylow** [comment]
This looks like it's only applying to one player in particular?
If it's not an actual issue that you can reproduce, you'll need to talk to the guy and understand maybe in what situation this happens. I'm pretty much flying blind in this situation because I have no way to know how this is happening as I can't cause the issue to occur.

**Comment by gravitylow** [comment]
Do you have any reproduction steps or more information?

**Comment by StarfireHunter** [comment]
He was the only player online at the time, thats why, all others where
owners/admins (who are exempt from checks)

**Comment by gravitylow** [comment]
So this happens to everyone on your server who does not have exempt permission? When does it occur? You have to understand I need to be able to make this happen to fix it.

**Comment by StarfireHunter** [comment]
It happens to everyone who does not have the exempt perm, it occurs when
they are mining/digging.

**Comment by gravitylow** [comment]
I played for about an hour today on a server with the latest build and have had no problems with either.

**Comment by Trikolon** [comment]
Fine for me as well.

**Comment by jojodmo2010** [comment]
@h31ix Sorry I haven't been able to respond, It happens when a player is either normally hitting other players, but it occurs most when a player is either: using sheers to get leafs, mining sugar-cane, or hitting thru/breaking vines. It happens with every player, even when I am watching the swing animation in process and they still get kicked, this plugin has way to many bugs

**Comment by gravitylow** [comment]
Does your situation align with the other described? It happens to everyone unless they have exempt permission? Also, can I get that debug log as mentioned in my first comment?

**Comment by jojodmo2010** [comment]
@h31ix It does happen to everyone if they don't have the exempt permission

**Comment by gravitylow** [comment]
Debug logs?

**Comment by jojodmo2010** [comment]
@h31ix http://pastebin.com/S6HSig0z

**Comment by gravitylow** [comment]
Can you try this on the newest release (1.5.6) and tell me if it's still an issue please?

**Comment by gravitylow** [comment]
Closed.
