### ISSUE TITLE
Time message in console

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#184]
Anticheat 431
This is happening in console when people are talking.
not present in the 429 version.

27.02 19:46:52 [Server] INFO [Member] kavanpro: without*
27.02 19:46:52 [Server] INFO Time: 4717
27.02 19:46:47 [Server] INFO [Member] kavanpro: withou the dot
27.02 19:46:47 [Server] INFO Time: 4078
27.02 19:46:43 [Server] INFO [Member] kavanpro: ./tpa kavanpro
27.02 19:46:43 [Server] INFO Time: 14849
27.02 19:46:35 [Server] INFO [Member] tomjeffx: how?
27.02 19:46:35 [Server] INFO Time: 35786
27.02 19:46:28 [Server] INFO [Member] kavanpro: tpa
27.02 19:46:28 [Server] INFO Time: 5404

**Comment by Trikolon** [comment]
Seems to be a debug-message, not really a bug. Would be cool if @h31ix could remove that. :)

**Comment by gravitylow** [comment]
lol

**Comment by Trikolon** [comment]
But its no bug at all I guess :)

**Comment by xsonarx** [comment]
yeah wasn't causing a problem ingame that i know of. thanks for fixing :) - i will again upload the new build later :)
