### ISSUE TITLE
Block glitching

### ISSUE THREAD

**Issue by pupnewfster** [gravitylow/AntiCheat#186]
I think it would be cool if you could add a method to stop players from block glitching over walls. I don't know how this could be done but even when the player is in adventure they can block glitch up onto things.

**Comment by gravitylow** [comment]
Could you elaborate? As you're describing it, it seems like AntiCheat's teleportation fix should cover this.

**Comment by gravitylow** [comment]
Any update on this?

**Comment by ryantheleach** [comment]
unsure what should cover this, but block glitching is where you place a block in an area which you arn't allowed to, jump on the block, then jump again before it gets removed, allowing you to climb up.

**Comment by gravitylow** [comment]
That isn't a hack, it's even caused by a plugin.

**Comment by ryantheleach** [comment]
well as far as the server is concerned the block never exists, its only client side until the client gets the update right?

**Comment by gravitylow** [comment]
Well the server still gets the packet and a plugin actively refuses the event which means for a while the client does think the event went through, but what does this have to do with this?

**Comment by ryantheleach** [comment]
Not necessarily, pretty sure you can do this in vanilla in the spawn
protected region.

**Comment by gravitylow** [comment]
In any case it's not an issue I can fix reliably.
