### ISSUE TITLE
Chat spam kick

### ISSUE THREAD

**Issue by Crazykool5** [gravitylow/AntiCheat#187]
Whenever my players say a certain amount of words, no matter how  long there are on they get kicked for spam, I turned spamkick off and gave everyone the bypass permission node in PEX. I've also parsed the YAML so theres nothing wrong with that.

**Comment by gravitylow** [comment]
Try running it on a server without any other plugins to make sure nothing is conflicting. As far as permissions goes, that's the fault of the permissions manager, not AC.

**Comment by gravitylow** [comment]
Any update on this?

**Comment by backwoods357** [comment]
I had this same issue with 1.4.7 a month back, the problem was with bkcommonlib. Update fixed the issue.

**Comment by gravitylow** [comment]
No update from OP so I'm closing this.
