### ISSUE TITLE
Admins are notified of a player that isn't online hacking.

### ISSUE THREAD

**Issue by iCake** [gravitylow/AntiCheat#188]
Issue: http://i.imgur.com/4I0zqZu.png
Plugins (Kits is custom): http://i.imgur.com/eRSPwI1.png
Bukkit version: http://i.imgur.com/tXiabOc.png
Report: https://dl.dropbox.com/u/56605228/AC-Report/report%20%231.txt

That should explain my issue.

Thanks!

**Comment by gdude2002** [comment]
Confirmed; we get this issue too. They aren't necessarily offline, but the player name and hack used are always the same.

Output in the console is normal.

**Comment by gravitylow** [comment]
Interesting. You're saying that the name displayed in console is correct, but the one showed to players is messed up?

**Comment by SuperSpyTX** [comment]
Damnit h31ix, not another spotty bug.

**Comment by gdude2002** [comment]
@h31ix It's not correct in the "Player is at X hacking level" message, but the red-coloured message that appears every time something is detected is correct.

**Comment by gravitylow** [comment]
Try http://ci.gravitydevelopment.net/job/AntiCheat/443/

**Comment by gdude2002** [comment]
Okay, it's up on our server. I'll get back to you.

**Comment by gdude2002** [comment]
@h31ix Nope, issue still exists. No change.

**Comment by iCake** [comment]
With the dev build, the issue is still there http://i.imgur.com/wexSg2Y.png

**Comment by gravitylow** [comment]
Thanks guys. I'll look into it a bit more but I'm kind of busy this week so it might be in my free spare minutes. Sorry about the whole issue, I know it's a bit obnoxious. Also I should add that despite how it looks it's actually due to very bizarre bugs that this happens, so it's not just a quick fix.

**Comment by gravitylow** [comment]
Fixed.

https://github.com/h31ix/AntiCheat/commit/4ee6e14153895175074953af59b3fc6b1f213411

Sorry about that taking so long, school and such.
