### ISSUE TITLE
Iventory Bug/Glitch (Shift Clicking)

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#189]
i can reproduce this over and over.

click an item in your inventory to select it (a stack of more then 10)
hold shift 
drag the item all around your inventory
then click somewhere 

user is able to kill him/her self with "user died" aka /kill msg.

this cant be done with permission. anticheat.check.fastinventory (aka bypassing the check)
make sure your in a default perm set nothing with *

AC: 455 and 459
Bukkit: #2653 and 2698

**Comment by gravitylow** [comment]
Should be fixed: https://github.com/h31ix/AntiCheat/commit/d021d29ac2f209c0dc59d5ab5fb5dfdc2ae000c6

Build: http://ci.h31ix.net/job/AntiCheat/457/

**Comment by xsonarx** [comment]
hopefully that is fixed will be back later when tested :)

**Comment by xsonarx** [comment]
AC: 1.5.7 (457)
Bukkit: #2663 - 1.5-R0.1

User can still kill them selfs. with out the invent bypass.

this affects legit players as well who arnt trying to kill them selfs but playing normal. one guy died using a furnace.

**Comment by gravitylow** [comment]
Still doing the shift click thing?

**Comment by xsonarx** [comment]
yeah can still kill my self with latest dev build. - i can provide the server ip if needed not sure if you can reproduce it ur side.

**Comment by xsonarx** [comment]
AC: 459
Bukkit: #2698

They die but stay on the server (glitched server side) cant interact in any way until they rejoin)

Still happens if they don't have the bypass invent check.

**Comment by backwoods357** [comment]
Any updates? This is a huge problem for us.

**Comment by gravitylow** [comment]
In my testing the update fixed this. I'm spending the weekend of spring break with family so please be patient.

**Comment by xsonarx** [comment]
yeah it still happens. they cant do it when i give the default rank the bypass check for fast inventory.

**Comment by xsonarx** [comment]
After updating to build #462 - it seems this has been fixed. - cant seem to kill my self with melon stacks now.

Thanks :)

Edit: Close ticket
