### ISSUE TITLE
Jumping in water push you back and log 

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#19]
When your jumping in a pool of water then your getting pushed back.
And it's logged as:
WARNING: {player} tried to walk on water.
Hope this can be fixed.
Last tested with Build #131

**Comment by SuperSpyTX** [comment]
@h31ix will have to look at this one.

**Comment by gravitylow** [comment]
Confirmed when a player is in one-block-deep water, attempting to fix this now.

**Comment by Rojoss** [comment]
Thanks

**Comment by gravitylow** [comment]
Try out build 135 http://ci.h31ix.net/job/AntiCheat/135/
See if the issue has been fixed.

**Comment by Rojoss** [comment]
Confirmed that it's fixed.
Thanks!
