### ISSUE TITLE
Doesnt block chat spam.

### ISSUE THREAD

**Issue by SimonErlandsson** [gravitylow/AntiCheat#196]
The newest dev build doesnt block chat spamming. It's really annoying.

**Comment by Trikolon** [comment]
For me it is working fine. Maybe run /anticheat debug     And post the result here.

**Comment by xsonarx** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by gravitylow** [comment]
Any update on this?
