### ISSUE TITLE
help my players keep getting hit

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#197]
Hey guys, When my players jump, they get damaged 1 heart? I tested it by myself and was not using any kinds of hacks. This is the error the console gave me: http://pastie.org/7113972

**Comment by xsonarx** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by gravitylow** [comment]
We spoke on IRC and determined that this was a conflict from running AntiCheat and NoCheatPlus at the same time. Don't do that. Throwing more chefs at a soup doesn't make it better.

**Comment by SuperSpyTX** [comment]
That's it, PR is coming.
