### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by cuddylier** [gravitylow/AntiCheat#20]
Hi,

I've got the latest dev build #131. The issue I am having is that none of the permission nodes are actually allowing my players to e.g. fly. It is still being blocked. This is especially the same with fast place and fast break even with creative.

Thanks

cuddylier

**Comment by SuperSpyTX** [comment]
Test this build http://ci.h31ix.net/job/AntiCheat/132/

Report back with console logs of the user fast breaking/placing or flying.

This is a basic permissions tester.  If these return false, Update PEX and try again, or reset your Permissions configuration.

**Comment by cuddylier** [comment]
Link says the website is offline :(

**Comment by SuperSpyTX** [comment]
Ok just wait until its back online.

**Comment by SuperSpyTX** [comment]
Apparently Cloudflare's retarded.

Here you go http://www.mediafire.com/download.php?dchc4nj9c2jw81o

This is the devbuild from the CI.
