### ISSUE TITLE
Taking Damage While Jumping

### ISSUE THREAD

**Issue by neth392** [gravitylow/AntiCheat#200]
My players take damage while they jump when holding shift for some reason, even in worldguard areas where they should be invincible

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

Also, please note the existence of 
https://github.com/h31ix/AntiCheat/issues/197

**Comment by neth392** [comment]
Well I dont run nocheat, only anticheat. And I believe I fixed it by disabling checks on nofall. And another problem I had was players getting falsepositives for falling a single block, but disabling nofall also fixed that, so nofall may be a little bit too sensitive.

**Comment by neth392** [comment]
http://pastebin.com/fgKnQUM1   Is the debug report too

**Comment by gravitylow** [comment]
As it says in my link you need to generate the debug report after the issue occurs but before you reload/restart so that I can see the logs. There are no logs in your report.

**Comment by neth392** [comment]
Oh sorry then. Well it hasn't occured since removing nofall so I guess you can close this, thanks anyways.

**Comment by gravitylow** [comment]
Thanks for the update.

**Comment by gravitylow** [comment]
._.
