### ISSUE TITLE
sprinted while standing still - but not using a mod

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#201]
If I need to edit the magic numbers could you advise on which line I edit?

these are legit players no mods - but anticheat picking them up.

This is with default magic.yml

Debug: http://pastebin.com/HvFrkA1C

**Comment by gravitylow** [comment]
There's no magic numbers for this check, it's just to see if the X and Y to/from positions stay the same when a person is sprinting. Can you watch someone while this happens and see whether there's some pattern, e.g. whenever this check occurs someone is sprinting up stairs or something like that.

That would help me be able to fix this.

**Comment by xsonarx** [comment]
I believe its when uses change level while sprinting - users have mentioned going up stairs does get them kicked sometimes. 

Edit:
http://pastebin.com/8H47Jb4c

this user wasn't going up stairs or anything, just joined my server and got kicked at the spawn point.
she looked like she was walking normal :S

**Comment by gravitylow** [comment]
Can you specify what you mean by "uses change level while sprinting"

**Comment by xsonarx** [comment]
I have a few dips in my spawn area that are half slabs dropping down to the next level it seems if they sprint into the hole type blocks it sets of the triggers.

http://imageshack.us/photo/my-images/5/20130330193050.png/

Edit
level meaning block level

isit possible to only check sprint on the same level? and ignore if going up/down levels? (not sure how this would work tho)
so they could basically sprint up mountins/stairs - aka cancel sprint check if level changes for so many seconds?

## 

it may not even be that I'm just throwing an idea at you :P

**Comment by xsonarx** [comment]
Still happening on the latest 1.5.7 version for 1.5.1.

**Comment by blablubbabc** [comment]
Here another report on that: http://pastebin.com/J1ZgmYVr

Proabably related to teleporting a player while sprinting ? This is just a guess..

**Comment by gravitylow** [comment]
I made this and spent like 5 minutes sprinting, juming, and walking over it. Got nothing :/
http://i.imgur.com/MP1wOGM.png

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
