### ISSUE TITLE
Taking Damage While Jumping [Again :/]

### ISSUE THREAD

**Issue by neth392** [gravitylow/AntiCheat#202]
Debug: http://pastebin.com/f0RsVb75

Well for some reason this started up again. My players take damage while jumping even with no fall disabled.

**Comment by gravitylow** [comment]
This is some sort of basic logic error I'm going to have to try and find the root of. Nothing that should require too much work; you can see there's an issue with it not evaluating whether 1 is greater than 10 for whatever reason.

**Comment by gravitylow** [comment]
Or maybe not... I fixed that faulty message in the latest dev build, from now on it should show the proper information. That probably won't fix this issue, but it will help me understand why it's happening.

**Comment by neth392** [comment]
Ok, so I just downloaded the latest dev build and I believe it fixed the problem. But for it to be fixed you need to delete  your old config. You should probably say that in the dev post or something unless this was only a problem for me. Thanks anyways :)

**Comment by gravitylow** [comment]
Config or magic.yml?

**Comment by neth392** [comment]
Well I just deleted the whole file tbh

**Comment by gravitylow** [comment]
The whole folder?

**Comment by neth392** [comment]
Yes, I deleted the anticheat plugin, then the anticheat folder, then installed the anticheat dev build and all was fine.

**Comment by gravitylow** [comment]
It seems like the magic.yml file would be the only thing that could change plugin behavior, so I'm going to assume deleting it would also have the same effect. I'm trying to figure out, though, which values that would have changed so that I can fix them from within the plugin instead of making everyone delete their files manually. Did you edit your magic.yml at all?

**Comment by neth392** [comment]
No, I didn't change anything. The only thing I did was give my users the permission that was somethign line              - -anticheat.checks.nofall  (This made it so nofall checks were disabled)

**Comment by gravitylow** [comment]
Right. Well, I've included a change that should reset magic.yml files when the build is run, so this should be solved.
