### ISSUE TITLE
Incorrect Logging?

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#203]
"null times"
"0 times"

Debug: http://pastebin.com/A79WSJWg

**Comment by gravitylow** [comment]
Does the release build fix this?

**Comment by xsonarx** [comment]
I think so, ill post back here if i see any weirdness.

**Comment by xsonarx** [comment]
CB: #2754
AC: 471
Magic.yml = default

[INFO|8:27:03]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:03]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:04]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:04]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:13]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:13]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:13]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:14]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:14]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:15]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:15]: westingtyler placed blocks too fast 0 times in a row (max=2) 
[INFO|8:27:15]: westingtyler placed blocks too fast 0 times in a row (max=2)
