### ISSUE TITLE
could anticheat allow players to break blocks in protected areas

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#206]
Worldguard Region -> user is able to glitch inside a block and it seems block is able to be smashed.

This also happens with grief-prevention that doesn't use worldguard.

not sure if this is down to anticheat but when the invent glitch was around that actually glitches you into the server and your still able to walk around doing stuff.

**Comment by gravitylow** [comment]
This is just a side effect of cancelling an event, since AntiCheat doesn't hook CraftBukkit there's nothing I could do about it even if I wanted to. If you wanted this fixed you would have to change something in the CB source.
