### ISSUE TITLE
Running on stairs -> fly, breaking blocks in too much distance, and other issues..

### ISSUE THREAD

**Issue by blablubbabc** [gravitylow/AntiCheat#208]
Hey,

my players are complaining about several things, even since before I updated to 1.5 and AntiCheat dev builds:
- being not allowed to break blocks in distance 6.0: I was even able to reproduce this myself by trying to break the upper log of a pretty (and) high tree: it showed me the break animation, but I was blocked because the block is in distance 6.0 and allowed is only 5.5 according to the log.
- players being detected as fly-hackers when walking on stairs: this issue already existed for my players BEFORE 1.5 . The report even shows a player being kicked because of this ( I walked behind him: he was normally walking up the stairs.. at least how I saw it.. )
- players being blocked from placing/breaking blocks because of "too fast placing/breaking". This already caused a player to fall into lava in the nether several times when trying to build a platform above it. Unfortunly I wasn't yet able to get this in the report..
- Sometimes: false Speedhacking detection. Can be caused by lag for exmaple by editing a great region with worldedit, teleporting, reloading.. Unfortunly, no report on that too.

For the two other see:
http://pastebin.com/v4SqNjG3

For some more log:
http://pastebin.com/W59Qgre1

Hope these can be fixed.. I hesitate from editing the magic.yml myself, because I am sure you know a lot better what settings are right..

However, I have the feeling that AntiCheat is very aggressive and false positives are made very quick and often.. :(
Would it maybe be possible to make the detection a bit "softer", less lag dependent or whatever is casuing all these false positives..? Maybe some sort of "soft"-mode which switches to another, softer magic.yml, which only detects people as hacking/cheating if AntiCheat is like 99,9 % sure. Even if this would mean to miss some hackers.. at least I could be sure again about the hackers it detects ..

Currently with how AntiCheat suspects people of cheating I can't tell for sure if players are cheating and if I should ban them / take actions on it.. there are too much false positives which makes it impossible for me to clearly differ between hackers and my few normal players which I do not want to loose.. I have this plugin running to clearly identify "bad players" and stop them. Currently I can't differ clearly and it stops everybody from having fun while playing :(

I would love to see such a "soft" magic.yml version provided by you sometime, instead having me trying out lowering some values, never being sure if I "over-lowerd" a value way too much.. It doesn't have to be exact: if a hacker isn't caught the first time, he propably will be detected in the future.. But when he is finally detected I can at least be sure and take the full set of actions on him without mercy / without having to find out if he reaally was hacking. Better that way than the current one in my eyes..

**Comment by blablubbabc** [comment]
Edit: I was able to get the fast placing into a debug report. The player was placing seeds, right in front of my eyes. 

Report: http://pastebin.com/nUbFseRK

**Comment by Trikolon** [comment]
I also have experienced the issue about Long-Reach
here my debug-report: http://pastebin.com/QgZ5W9tE (See player piggy501).
It occurs when cutting down high trees.

EDIT:
Solved the problem by editing the magic.yml value for BLOCK_MAX_DISTANCE from 5.5 to 6.0 (As this is the regular Minecraft distance when digging upwards)

**Comment by blablubbabc** [comment]
Here is a report of a player being kicked for flying even though he simple was running around. Even not on stairs.
http://pastebin.com/gSbE7FL4

**Comment by gravitylow** [comment]
I pushed a fix that corrects the reach distance, but I'm going to have to close this ticket. This is just... too much. You can't do this - creating so many issues in one report. I can't keep track of it, and commenting on unrelated topics with a debug report for a new bug you need to report isn't helpful. 

If you would like me to keep track of these, please submit a specific ticket containing reproduction steps and a debug report for EACH.

**Comment by blablubbabc** [comment]
" Update reach distances for creative mode "

The long reach thing is also happening in survival mode. This one is very easy to reproduce by trying to cut the upper log block in a hight tree.

**Comment by Trikolon** [comment]
"Solved the problem by editing the magic.yml value for BLOCK_MAX_DISTANCE from 5.5 to 6.0 (As this is the regular Minecraft distance when digging upwards)"
