### ISSUE TITLE
shift-clickdrag in chests

### ISSUE THREAD

**Issue by rbos** [gravitylow/AntiCheat#209]
I've had a couple of players complain about, when doing shift-clickdrag on a chest to spread multiple single-blocks through that chest (sigh), that the player instantly dies and loses their inventory. I've had a few people confirm that this happens, even with the version released yesterday.

Disabling the nocheat fastinventory check seems to prevent this.

I'd just like to check if anyone else is having this issue and report it if not.

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by xsonarx** [comment]
@ rbos

https://github.com/h31ix/AntiCheat/issues/189

Can you confirm that the inventory glitch that does the same thing is fixed on your server?
it should be fixed.

**Comment by rbos** [comment]
I removed the exemption and tested it, with 1.5.7. I did not get instant-killed. So it is probably fixed.
