### ISSUE TITLE
Multiverse TP's (False Alarms)

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#211]
DEBUG: http://pastebin.com/vvWmDq2E

This is with Multiverse TP's 

User goes through TP
User gets thrown up and down 
somehow they are moving to fast to trigger these events

This sets off 2 alerts/kicks
NAME tried to fly on y-axis XX times (max =1) (spams this)
NAME sprinted while standing still (xyz = 1,6,-1) (spams this)

Edit
If a user types /home (some times it triggers the sprint event if they don't stand still for a few seconds after going home)

**Comment by gravitylow** [comment]
Hey, where is the teleporter pointing to? The same world or a different world?

**Comment by Trikolon** [comment]
Known issue. Also had this problem, somehow solved itself.

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
