### ISSUE TITLE
How to do away with Fastplacing and Fastbreaking?

### ISSUE THREAD

**Issue by Rotatoed** [gravitylow/AntiCheat#212]
How can I just get rid of the fastplacing and fastbreaking part of the plugin?

**Comment by xsonarx** [comment]
All info can be found here: https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by gravitylow** [comment]
AntiCheat permissions: http://dev.bukkit.org/server-mods/anticheat/pages/permissions/
