### ISSUE TITLE
Cant Attack Mobs/Players.

### ISSUE THREAD

**Issue by NLBlackEagle** [gravitylow/AntiCheat#213]
After a full day of doing research I found out that Anticheat was causing/triggering the problem. I've tried using the anticheat.check.exempt permission but this wont work.

Ill might provide more info in the future but this Is all I could say at the moment.

Greetings, Eagle

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by gravitylow** [comment]
Closing
