### ISSUE TITLE
Jenkins (Offline)

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#215]
## https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

Page loads but only a snapshot that is maybe 3-6 days old
Development Builds --- http://ci.gravitydevelopment.net/job/AntiCheat/

Page loads but only a snapshot that is maybe 3-6 days old
http://ci.h31ix.net/job/AntiCheat/
Last Build: #467 Apr 4, 2013 5:47:03 PM

**Comment by gravitylow** [comment]
![image](https://f.cloud.github.com/assets/615294/368751/e251a3ac-a2c7-11e2-8376-a39fcf464bcd.jpg)

**Comment by xsonarx** [comment]
anything i view from http://ci.h31ix.net/ - gets the offline snapshot message - along with slow loading.

it was working fine a few weeks ago.

**Comment by Trikolon** [comment]
Works fine for me.

**Comment by xsonarx** [comment]
I even click "hide this alert" refresh and its back telling me its offline? but no other site that users cloudfare has problems. 

not sure whats going off.

**Comment by gravitylow** [comment]
It sounds like an issue on your end rather than my problem.

**Comment by xsonarx** [comment]
I cant even load the login page over there on your jenkins page - it pops up with the CloudFlare message/page.

http://ci.h31ix.net/login?from=%2Fjob%2FAntiCheat%2F
This website is offline
No cached version is available

http://www.cloudflare.com & nsanedown (that users cloudflare) works fine.

Edit
This is at the bottom of the page, I'm guessing its the snapshot from the 6th?
Page generated: Apr 6, 2013 4:21:20 PM

Edit
why is my ip being blocked? - I use a vpn/proxy and it works?
This may not be your side but its definitely cloudflare

I go in through proxy and get 
Page generated: Apr 11, 2013 6:41:07 PM

**Comment by gravitylow** [comment]
@xsonarx could you hop on IRC sometime or PM me your IP so I can check it on cloudflare?

**Comment by gravitylow** [comment]
Closing this.
