### ISSUE TITLE
Flyhack for sprinting on stairs (and sometimes even on normal ground)

### ISSUE THREAD

**Issue by blablubbabc** [gravitylow/AntiCheat#218]
players being detected as fly-hackers when walking on stairs: this issue already existed for my players BEFORE 1.5 . The report even shows a player being kicked because of this

http://pastebin.com/v4SqNjG3

And here is a report of a player being kicked for flying even though he simple was running around. Even not on stairs.
http://pastebin.com/gSbE7FL4

I can't tell how to reproduce, unfortunly. I can only tell what players tell me and every of my 5 players seems to have this issue form time to time..

**Comment by eljek** [comment]
Got exactly the same problem. 
Here you go.
http://pastebin.com/V6x4cuZf
Anbody got any idea how to fix this? Perhaps some changes in the magix.yml or something like this. Help is much appreciated.

**Comment by gravitylow** [comment]
@Morgoth144 @blablubbabc are these guys just walking up stairs? or running? is it indoors or outside? what kind of stairs?

**Comment by blablubbabc** [comment]
I think I remember the last time I was able to see this happen to a player right in fornt of me, he was running upstairs inside.

**Comment by eljek** [comment]
Well, it was inside, a cobblestone stair down to my mining shaft. When you sprint this stair upwards you get kicked for flying. Have tried to reinstall the plugin, but the problem still occurs.. Btw. love your mod :)

**Comment by blablubbabc** [comment]
Exactly same situation :)

**Comment by blablubbabc** [comment]
Thanks! Hopefully this will work :)
