### ISSUE TITLE
False Speed hacking kick on lag

### ISSUE THREAD

**Issue by blablubbabc** [gravitylow/AntiCheat#219]
false Speedhacking detection. Can be caused by lag for exmaple by editing a great region with worldedit, teleporting, reloading..

If a player is running right in the momment of when I do something that causes a short amount of lag, like reloading a big plugin, the player is kicked for sprint/speed hacking.

Nearly everytime, if the player was running in just this moment.

I can't tell if this is something you can fix.. as it is something that reallyis caused by server lag.. It guess many false positives are caused by server lag spikes.. :(

**Comment by gravitylow** [comment]
Please include a specific debug report of this happening.

**Comment by blablubbabc** [comment]
http://pastebin.com/HUf6bbYk

**Comment by blablubbabc** [comment]
I just see, this could be realted to: https://github.com/h31ix/AntiCheat/issues/201

**Comment by blablubbabc** [comment]
the player was sprinting, then I did a plugin reload with a plugin manager, which lags the server for half a second or so and teleports the player to spawn.

**Comment by gravitylow** [comment]
And you're referring to the "Domi" player in the logs?

**Comment by blablubbabc** [comment]
Ps: all log entries in this report by the players "opagandalf1992", "Domi0304" and "decoda91" are false positives.. These players definetly do not cheat, still anticheat logs that they seem to do so. :(

**Comment by blablubbabc** [comment]
Yes
He was the player I just tested it with

**Comment by gravitylow** [comment]
Right so as I understand it you used a plugin that caused a bit of lag and also teleported the player in question. The log then became spammed with "sprinted while standing still" messages until he was kicked?

What about on the player's end? What did he see when this happened? Was his screen glitching around?

Was he teleported inside something like a portal or an enclosed space? Or was he in the open?

**Comment by gravitylow** [comment]
Wrong button -- get back to me on those so I can sort this out, if you please.

**Comment by blablubbabc** [comment]
Okay I just asked him: before he was kicked he only saw the sky (like just after an teleport and the world doesn't load)

And I have to correct myself: the player gets not teleported to the spawn, but to some location in the world. In this case it was into some forest somewhere. After rejoining the server then everything was fine again.

**Comment by gravitylow** [comment]
And the spamming happened after the reload/teleport but before he got kicked, correct.

**Comment by blablubbabc** [comment]
Spamming? You mean the log entries ? This is the output of when I typed /anticheat debug , so yes. And I got a warning, a second warning and the kick message in-game, just like listed at the top of the log

**Comment by gravitylow** [comment]
The spamming of "sprinted while standing still.."

**Comment by blablubbabc** [comment]
"And the spamming happened after the reload/teleport but before he got kicked, correct."

After the reload, which inits the teleport during which he gets kicked. You can actually see that in the debug report, no ?

Anticheat detects in the reload/teleport phase that the player is hacking and decides to kick him after a certain time. I think just after the reload is finished etc.. but I am not sure as this reload phase is shorter than 1-2 seconds.

**Comment by gravitylow** [comment]
That's the info I was asking for; I can see the debug log but it's not a full server log, just AntiCheat events, so I need context for it.

**Comment by Soz3r** [comment]
Any further progress in this bug?  

I have a circumstance where the world saves, user riding a boat gets flagged "{user} sprinted while standing still @ x,y,z" and in the midst of it he did /afk.  Heres the log  http://pastebin.com/NDRFR2wz  - There are so many factors at play its hard to identify the source of the problem.  

Although, the player said there were missing chunks that we weren't loading, causing them to teleport.

Maybe put an IF () THEN () statement that requires so many chunks of the surrounding world to be confirmed loaded prior to execution of a cheat flag... is that possible/probable/practical?   Just trying to help although i'm don't know the scope of the variables/controlables...

Also note https://github.com/h31ix/AntiCheat/issues/201 is the same...

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
