### ISSUE TITLE
Error on Console

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#22]
http://pastebin.com/cVBb3tX6

Version #135
CB 2211

**Comment by SuperSpyTX** [comment]
I'm sorry, but no context means no issue.

**Comment by SuperSpyTX** [comment]
Did not look at IRC before checking issue.

Apologies.

**Comment by gravitylow** [comment]
You have a config that has no setting for an event, that's not an actual bug. Easy fix is delete your config, reload/restart your server, or type /anticheat reload.
