### ISSUE TITLE
Providing an more soft and less lag dependent magic.yml

### ISSUE THREAD

**Issue by blablubbabc** [gravitylow/AntiCheat#220]
Hey,
I have the feeling that AntiCheat is very aggressive and false positives are made very quick and often.. :(
Would it maybe be possible to make the detection a bit "softer", less lag dependent or whatever is causing all these false positives..? Maybe some sort of "soft"-mode which switches to another, softer magic.yml, which only detects people as hacking/cheating if AntiCheat is like 99,9 % sure. Even if this would mean to miss some hackers.. at least I could be sure again about the hackers it detects ..

Currently with how AntiCheat suspects people of cheating I can't tell for sure if players are cheating and if I should ban them / take actions on it.. there are too much false positives which makes it impossible for me to clearly differ between hackers and my few normal players which I do not want to loose.. I have this plugin running to clearly identify "bad players" and stop them. Currently I can't differ clearly and it stops everybody from having fun while playing :(

I would love to see such a "soft" magic.yml version provided by you sometime, instead having me trying out lowering some values, never being sure what I am doing there.. It doesn't have to detect "small hacking", or detect hackers fast and at the first attempt, if trying to detect them that prcese is vulnerable to false positives as it currently seems. It doesn't have to be exact: if a hacker isn't caught the first times, he propably will be detected in the future.. But when he is finally detected, when trying out to hack some more and aggressive for example, I can at least be sure and take the full set of actions on him without mercy / without having to find out if he reaally was hacking. I would prefer that over the current situation...

**Comment by SuperSpyTX** [comment]
The other way is enabling Silent mode.

**Comment by blablubbabc** [comment]
I don't want to disable AntiCheats automatization. AntiCheat shall still automatically kick hackers, just not "that aggressive" (means kicking less to zero non-hackers). And even in silent mode, it will alarm me I guess that a player is "hacking" so i can take actions myself. The problem with that is, like pointed out above, that this "hint" is currently nearly worthless for me as I currently can't be sure if something is just another false alarm, or a serious hacking player..

**Comment by SuperSpyTX** [comment]
If you want something less serious, you either fine tune the settings in magic.yml.

There's no such thing as soft-"magic.yml"

Disable a few checks (via permissions) if you want to make it seem less serious, there are checks in AntiCheat that I am for sure granted that work very well.

**Comment by blablubbabc** [comment]
"If you want something less serious, you either fine tune the settings in magic.yml.

There's no such thing as soft-"magic.yml""

That's why I ask for one. And I would prefer that someone who actually has the experience about the meaning of the different values, like knowing what are good bounds and what not, to edit it, instead of me "trying out". I don't want to disable it, I just would like it to be less aggressive.

"there are checks in AntiCheat that I am for sure granted that work very well"
And of course I am not talking about the checks that already work like 99,9 % sure.

If everything would work already that well and AntiCheat would throw none to very few false positives, I would not be here and ask for such an less precise option.

**Comment by SuperSpyTX** [comment]
There probably won't be one then because it would be stupid if you could just configure it on your own.

**Comment by blablubbabc** [comment]
"if you could just configure it on your own"

But I am not that experienced with what different values for the different settings would practical mean and what are the bounds for "good values" (max - min), to still be not "disabled".

**Comment by gravitylow** [comment]
Nobody is going to be able to configure it for you; it's your server.

**Comment by blablubbabc** [comment]
YOU are able to configure it. My server is just like everyones server.

Also it's your plugin and it's not working that well :(
There is no day without my few players flaming about it.

And it's not only me having lot's of false positives (just like users of NoCheatPlus have too unfortunly, to be fair: I just still like AntiCheat more for it's easieness). And of course I don't know if thats really related to the settings, but this is my guess.

So that's why I am here to ask for softer and hopefully better working settings.
By "better working" I don't mean "more precise in checking" (means: it can "oversee" some, only less hacking players sometimes -> hopefully less lag dependent then), but "more precise in detecting" (means: a player is detected -> I can be sure it's no false positive and he was defenetly hacking)

Of course not everyone will share my opinion in what is more important: precise checking <-> precise detecting
That's why I just asking for an additional option, to try out to see if things work better that way.

Having such softer settings and finding out they work quit well would help everyone. 
Who would be better in finding such settings than you, the author, who has all the insight in how these settings and minecraft default behavior is working (?)

**Comment by gravitylow** [comment]
Errr... yes, I am able to configure it. And I have. I make AntiCheat work for me - if it doesn't work the same for you that's a difference on your end. Servers are not all the same, in any respect. 

You're under the impression that I can just provide a "better" magic.yml that isn't as demanding. I cannot, that would take an entire codebase change. The Magic.yml system was created so that you could lessen the requirements of a specific check, and you're not intending on doing that. You're instead acting like the whole system just needs to be "better". That's not a bug report I could work on.

"Precise checking" can be improved only if you report specific bugs. As I said earlier, I make the system work on my server and get feedback from others. I'm not going to sit around configuring people's magic.ymls just because I know how they work best; the point of creating it was putting that in your hands. I'll handle the code, you fiddle with the values or report SPECIFIC bugs if that doesn't work.

**Comment by blablubbabc** [comment]
okay ..
