### ISSUE TITLE
Inventory check false positive

### ISSUE THREAD

**Issue by DarkArc** [gravitylow/AntiCheat#224]
Described here: https://github.com/h31ix/AntiCheat/commit/c3b77764ba36b888455c89a33e7063c336c6ed84

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by DarkArc** [comment]
http://pastebin.com/XxsWyr6b

**Comment by gravitylow** [comment]
I don't see anything about inventories in the logs. As I say in my link, you need to generate the report AFTER the issue has occurred and BEFORE you reload/restart the server.

**Comment by DarkArc** [comment]
Sigh then you will have to wait. I presume that you cannot reproduce this issue?

**Comment by gravitylow** [comment]
No, I was under the impression it was fixed: https://github.com/h31ix/AntiCheat/commit/d021d29ac2f209c0dc59d5ab5fb5dfdc2ae000c6

**Comment by DarkArc** [comment]
If this helps at all here's sk dev's version http://pastebin.com/sngg86PY

I also have several custom coded plugins loaded through commandbook, though none mess with the InventoryClickEvent. I hope this will be a bit more useful, unfortunately I'm in a position where console output is all I can get at the moment.

**Comment by gravitylow** [comment]
On your server InventoryClickEvent is registered by:
- LWC
- CommandBook

**Comment by DarkArc** [comment]
Neither of those should be doing anything aside from cancellation... That couldn't cause the issue could it?

**Comment by gravitylow** [comment]
I don't know, but I haven't looked closely into either of them. I haven't heard reports of this since I pushed that fix, so I was under the impression it had been resolved.

**Comment by DarkArc** [comment]
Unfortunately not, it just causes inventory loss instead of death now.

**Comment by DarkArc** [comment]
There is one commandbook mod I have that would cancel the click event(forgot about that one my apologies). I've glimpsed over your code though, it seems only creating and calling more events would make that check fail...

**Comment by DarkArc** [comment]
Also I'd like to point out that this isn't from right click. It's when you are holding say a block of dirt while you have say a chest open and you double left click a dirt block while holding shift and all the dirt blocks in the inventory you clicked transverse to the other inventory.

**Comment by gravitylow** [comment]
As far as I know the API that was in place (it's being improved) applied to that situation. The whole new dragging actions and collecting actions are technically right click functions, and so they're covered by that commit.

**Comment by gravitylow** [comment]
Please re-open this ticket (or reply) when you've got a debug log. Thanks.

**Comment by DarkArc** [comment]
http://pastebin.com/9CQ8X83N - There ya go

**Comment by gravitylow** [comment]
This also has nothing to do with inventories. There are no logs indicating any checks failed of the sort.

**Comment by DarkArc** [comment]
Line 28: "Dark_Arc clicked inventory slots 10 times in 1 ms (max=10 in 50 ms)"

**Comment by gravitylow** [comment]
Oops -- missed that one. I'll look into this.
