### ISSUE TITLE
Checks ignore potion effects

### ISSUE THREAD

**Issue by lenis0012** [gravitylow/AntiCheat#229]
Whenever a player gets a potion effect AntiCheat doesn't really take care.

When you drink a speed potion and start running you get kicked for fast run hacks.
And jump potione ffects let you get kicked for superjump.

Annoying when you have jump ads and free speed potions in your server ;)

**Comment by gravitylow** [comment]
I wasn't able to generate false-positives from either speed potions or jump effects from beacons.

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
