### ISSUE TITLE
Fast break/place issue and Fly issue with stairs

### ISSUE THREAD

**Issue by x0Z3ro0x** [gravitylow/AntiCheat#230]
So ill keep this short and simple. I have issues with people being kicked for fast placing and breaking. They can only place 3-4 blocks at a time before getting warned or kicked. 

The second issue I am having is users walking or sprint jumping up or down stairs and getting BANNED for it. This is a huge issue for me but I love your plugin. Please fix these issues or tell me how.

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions
