### ISSUE TITLE
TNT False Positive

### ISSUE THREAD

**Issue by DarkArc** [gravitylow/AntiCheat#231]
Hurting a player with TNT triggers a false positive of the no swing check.

http://pastebin.com/X2fLNcNc

**Comment by gravitylow** [comment]
Can you point out where that is in the log?

**Comment by DarkArc** [comment]
Lines 25, 28, 31, 34, 37. (that's not all of them, but ya)

**Comment by DarkArc** [comment]
So I wrote this: 

``` java
    @EventHandler(ignoreCancelled = true)
    public void onEntityDamagedByEntity(EntityDamageByEntityEvent event) {

        Entity attackingEntity = event.getDamager();
        Entity defendingEntity = event.getEntity();

        if (!(defendingEntity instanceof Player)) return;
        Player defendingPlayer = (Player) defendingEntity;

        Player attackingPlayer;
        if (attackingEntity instanceof Player) {
            attackingPlayer = (Player) attackingEntity;
        } else if (attackingEntity instanceof Arrow) {
            if (!(((Arrow) attackingEntity).getShooter() instanceof Player)) return;
            attackingPlayer = (Player) ((Arrow) attackingEntity).getShooter();
        } else {
            defendingPlayer.sendMessage("Attacked by: " + attackingEntity.getType().toString());
            return;
        }

        attackingPlayer.sendMessage("You've hit " + defendingPlayer.getName() + "!");
        attackingPlayer.sendMessage("Damage Type: " + event.getCause());
    }
```

To play around with this. It seems you get hit by the tnt (when it is lit by a player using flint and steel) and then a separate event is fired for the player him/herself...

**Comment by gravitylow** [comment]
So you're saying there's an instance where event.getDamager() will return a player instance (instead of, say TNTPrimed) when an entity is damaged by a TNT block lit by that player?

**Comment by DarkArc** [comment]
Ya, pretty much...

**Comment by gravitylow** [comment]
Confirmed. Looking into why this is.

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
