### ISSUE TITLE
False Issues

### ISSUE THREAD

**Issue by homestar52** [gravitylow/AntiCheat#232]
No one likes AntiCheat (players or admins) because it is VERY glitchy/bugged/messed up. Here are just a FEW of the issues many are having:

False fastplacing
False fastbreaking
False fly hacking on the y/x-axis
False "If you continue to hack..."
False "Please stand still to prevent getting damaged..." (I don't even know what it says!)
False EVERYTHING!!!!!!!!!!!!!! THIS PLUGIN GOES TOO FAR AND PREVENTS EVERYTHING!!!!! JUST NOW I WENT THROUGH A PORTAL FROM MULTIVERSE, AND IT DIDN'T LET ME MOVE BECAUSE OF THIS PLUGIN!!!! WITHOUT THIS, YOU CAN DO PARKOUR, PVP, AND EVEN MOVE AROUND!!!!! THIS GOES TOO FAR!!!!!!!

**Comment by gravitylow** [comment]
Read https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions and repost when you've calmed down.

**Comment by homestar52** [comment]
Wow, calm down.
