### ISSUE TITLE
Players Can Still Hack While Using Nodus

### ISSUE THREAD

**Issue by XvBaseballkidvX** [gravitylow/AntiCheat#233]
Hello everyone, my friend and I have been messing around with the AntiCheat and what it can protect which should be all of the hacks. But I he has found a bug. When using Nodus, if you turn on derp and set the mode to hump(I know this sounds really stupid but it indeed works), you are able to fly and high jump. I am not sure why this happens or what I can do to prevent this. If you are able to fix this bug I will be very grateful, thank you for reading.

Magic.yml:

http://pastebin.com/yrHXgzQu

**Comment by DarkArc** [comment]
I'll save h31ix some time and ask you to look at https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions :)

**Comment by gravitylow** [comment]
Please reopen when you've got a debug report.
