### ISSUE TITLE
Will you please add  compatibility for Vampire plugin

### ISSUE THREAD

**Issue by prophetnoble** [gravitylow/AntiCheat#237]
I realy need compatibility for Vampire plugin need Anti-cheat and We all use vampire on my server i cant stop it for stoping high jump in /vp bloodlust wacth makes it were vampire run and jump faster and higher

**Comment by gravitylow** [comment]
You must ask the developer to implement our API. http://dev.bukkit.org/server-mods/anticheat/pages/api-documentation/
