### ISSUE TITLE
Player getting kicked for hacking while going through Multiverse portals

### ISSUE THREAD

**Issue by rnoa** [gravitylow/AntiCheat#238]
Got this issue. Players get kicked for hacking while going through Multiverse portals. Different "hacks" everytime, mostly sprint, but could be speed and even spam. Please help!

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by rnoa** [comment]
Oh, thanks, here comes my pastebin after anticheat debug command http://pastebin.com/gs2HjqxP I believe the repeated lines about people sprinting while standing still were when they went through the portals.

**Comment by gravitylow** [comment]
Is this a reproduceable bug? ie. does it happen every time you do something, or just sometimes?

**Comment by rnoa** [comment]
Sometimes and more often with certain players and less or never with others, but I believe it has increased lately.

**Comment by gravitylow** [comment]
Weird. I'm not able to get it to occur at all on my server.

**Comment by DarkArc** [comment]
Oh! Multiverse Nether portals? I just remembered in some cases it will throw the player if it thinks the portal doesn't have a destination.

**Comment by rnoa** [comment]
DarcArc, that has happened in my server too, but the most annoying thing is with usual multiverse portals. Hmm, what should I do?

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
