### ISSUE TITLE
DUplication bug with nodus

### ISSUE THREAD

**Issue by unknownun** [gravitylow/AntiCheat#239]
Hi, i have found a bug for duplicate items: http://www.youtube.com/watch?v=70vlo5UM4v8&feature=youtu.be Please fix it

**Comment by gravitylow** [comment]
Dealing with duplication bugs are not my problem. If there's a dupe bug, it should be reported IN PRIVATE to Bukkit, not me in the public. However, in my own testing this doesn't work.
