### ISSUE TITLE
Swimming Under Block Fail

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#24]
When a player is swimming and they are underneath a block, for example a player was underneath his castle swimming below it, and he was glitching backwards- It was rubber-banding him.

**Comment by SuperSpyTX** [comment]
Care to pastebin some console logs?

**Comment by Murabitos** [comment]
Yeah i'll enable debug and have him do it again..

**Comment by Murabitos** [comment]
[WARNING|5:25:32]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:33]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:35]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:36]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:38]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:38]: [AntiCheat] coll6 tried avoid fall damage. 
[WARNING|5:25:38]: [AntiCheat] [ALERT] coll6 has entered the MEDIUM hack level. 
[WARNING|5:25:38]: [AntiCheat] [ALERT] This means they may be using a hacked client or may have a bad connection! 
[WARNING|5:25:42]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:42]: [AntiCheat] coll6 tried to walk on water. 
[WARNING|5:25:43]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:45]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:49]: [AntiCheat] coll6 tried to fly. 
[WARNING|5:25:50]: [AntiCheat] coll6 tried to fly.

**Comment by gravitylow** [comment]
I saw the issue very mildly, so I'm going to do some more testing and work on this. Thanks.

**Comment by Murabitos** [comment]
Thanks, I thought it was pretty weird that he was sending off tons of different messages.. If you're still having trouble I think I could let you on my server and teleport to him as he does it. let me know what dev build to update to when it's fixed, thanks!

**Comment by gravitylow** [comment]
Fixed this here: https://github.com/h31ix/AntiCheat/commit/51679148fe5ce13c70d09d86b06f6a48c6d1a3ea and in this dev build: http://ci.h31ix.net/job/AntiCheat/143/

This also helped me discover a really big bug that I overlooked in 1.2, so thanks, this change will be present in a 1.2.1 release that we plan to do today to fix these issues.
