### ISSUE TITLE
Fast break/place issue and Fly issue with stairs

### ISSUE THREAD

**Issue by johnjuhl** [gravitylow/AntiCheat#241]
There was another post with this issue that you closed because he didn't include the debug I asume.  http://pastebin.com/wcuRpRtE

For now I have doubled the leniency on all of the y-axis options in magic.yml

**Comment by gravitylow** [comment]
https://github.com/h31ix/AntiCheat/issues/218

http://ci.gravitydevelopment.net/job/AntiCheat/484/
