### ISSUE TITLE
Unable To Load AntiCheat

### ISSUE THREAD

**Issue by SuperPyroManiac** [gravitylow/AntiCheat#242]
I wanted to see how AntiCheat would compare on my server to NoCheatPlus. I disabled NC+ and put Anticheat.jar in my plugins folder to let it generate a new plugin folder, but instead it does this.

http://pste.me/v7OUb

**Comment by SuperPyroManiac** [comment]
Latest Dev build fixes this issue. Although you still may want to look into this.

**Comment by gravitylow** [comment]
" Could not load 'pluginsAntiCheat.jar' "
This seems like a setup issue to me

**Comment by SuperPyroManiac** [comment]
I tried it both on my localhost server and my main server. Error was same on both.

**Comment by gravitylow** [comment]
What operating systems did you try it on? And I'm assuming you're using the latest release version (1.5.8)?

**Comment by SuperPyroManiac** [comment]
Yes, but the issue is fixed in the latest dev build. Although im curious to what's causing the error. As I get it from multiple plugins now.

I tested this on my localhost server same error (Windows 8)
And my main server (Linux)

**Comment by TnTBass** [comment]
Looks to be caused by a corrupt download to me.
