### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by SuperPyroManiac** [gravitylow/AntiCheat#243]
Here are some major issues I have found when using Anticheat. I normally use Nocheat but anticheat is really nice and when it does send alerts most of the time it is true. In this case Anticheat sends a medium hack level alert for these but does nothing about it.

Survival Nuker
Fast Projectile (Throwing potions or shooting arrow instantly)
Forcefield/Kill Aura

And if you sprint up stairs, it flips out and tells you that you are flying.

I really hope these can get fixed! Thanks ahead of time.

**Comment by gravitylow** [comment]
Closing issues that are very old and (sometimes) not relevant anymore to the current version. As I push towards a 2.0 release, I need to know which issues to focus on for the upcoming polish. If you are still experiencing issues mentioned here, please open a new ticket and describe how they can be reproduced using the latest dev build.

Thanks!
