### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KosmonavtPad** [gravitylow/AntiCheat#249]
Hellow .
I found a bug by which cheaters can use cheats and AntiCheat will not see they.The plugin consists of several files. But the  settings behavior  of the plugin are in the file Events.yml
By default, the plugin will kick players whose rating is 50 . But when the plugin performs a kick they ,  players can go to the server again and continue to use cheats  and Anticheat will not kick him .The same will happen if instead of kick to put the ban . If unban player after that, the Anticheat will not ban him.
Anticheat ver:1.5.2

**Comment by gravitylow** [comment]
Levels have been capped at the highest level.
