### ISSUE TITLE
isolated issues are logged as SEVERE but should be INFO

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#25]
When an issue gets logged, it looks like this:
[SEVERE] [AntiCheat] xxxx tried avoid fall damage.
[SEVERE] [AntiCheat] xxxx tried to walk on water.
[SEVERE] [AntiCheat] xxxx tried to break a block of STONE without swinging their arm.

These used to be WARNING and now they are SEVERE, but they really should just be INFO since they are isolated incidents that are often not really problems, but lag induced.

If a player's threat level gets moved up, that's a good WARNING.

SEVERE should be reserved for a major error or perhaps a player being KICKED.

As a server admin, if I see SEVERE, I stop whatever I'm doing to investigate.

Request is to change these to [INFO] messages so admins don't get concerned when they don't need to.

**Comment by gravitylow** [comment]
Confirmed, this was an issue I saw but did not worry about before pushing a release, It's some issue that popped up when  I was switching the logger to fix your other issue. I'll investigate.

**Comment by ZathrasNotTheOne** [comment]
On server stop...

[SEVERE] [AntiCheat] Disabling AntiCheat v1.2.1

**Comment by gravitylow** [comment]
Fixed: http://ci.h31ix.net/job/AntiCheat/170/
