### ISSUE TITLE
click detection

### ISSUE THREAD

**Issue by drtshock** [gravitylow/AntiCheat#251]
Check clicks per second to prevent kill aura and other things.

**Comment by drtshock** [comment]
Other things:

Add prefix when you log to console (easier to grep the file for a player).
False positive when sneaking and getting hit by knockback.
Player that was stuck in a block through a warning for ascending too quickly.

**Comment by gravitylow** [comment]
Added to the version 2.0 milestone.

Please file a separate issue with more detail for the last one.
