### ISSUE TITLE
No way to whitelist commands from command spam check

### ISSUE THREAD

**Issue by HaxtorMoogle** [gravitylow/AntiCheat#256]
There are some commands that have to be typed fast for some plugins to work right or be useful. 

For example:
- Auction Plugins
- LWC, adding another player to all your protections
- Towny, Setting up a town and tons of town blocks

Players are getting kicked for no reason :(

**Comment by gravitylow** [comment]
https://github.com/gravitylow/AntiCheat/commit/c6d232d49334ff4832d20b68b7cf3d377174fc55
Added! Thanks.
