### ISSUE TITLE
False Positive : flying during creative mode

### ISSUE THREAD

**Issue by DoubleSixFS** [gravitylow/AntiCheat#257]
Hi , i'm FirmanSahita
i found a problem from your plugins

Known Problem :
1. flying during creative mode (fly with running in creative mode)
2. flying during creative mode + sneak when flying (fly and fall down with sneak on air in creative mode)

i hope AntiCheat plugin has fix that problem :)

**Comment by gravitylow** [comment]
I wasn't able to duplicate either of these issues on the newest beta.
