### ISSUE TITLE
Wall-Chest-Cheat

### ISSUE THREAD

**Issue by Kowagirl** [gravitylow/AntiCheat#26]
If you have freecam you can use it to open a chest on the other side of a wall.
Me doing it: http://www.youtube.com/watch?v=u9ZleuirT2o

P.S. I was listening to call me maybe at the time. Just mute the audio. ;)

**Comment by SuperSpyTX** [comment]
I am going to work on this.

**Comment by Fogest** [comment]
@SuperSpyTX take note it's more then just chests that can be opened. Users can also do things such as breaking into protected areas and even pulling levers and pressing buttons in areas they normally could not get to. It's really a bad thing on faction servers as people can break into protected areas. The chest part would probably be easier. Check if the user is facing the same direction of chest and that there are no blocks within the line of sight. 

It may be harder to protect against breaking into a building though.

**Comment by SuperSpyTX** [comment]
@Fogest If that's the case, i'll make it so whatever they're hitting something, it'll check it just like the chest cheat.

**Comment by Fogest** [comment]
Sounds good. It would be awesome if this could be patched asap, as it's
really a big factor in faction servers. It's hard to make bases that
prevent from this sort of glitching. Looking forward to this being
implemented!

On Mon, Jun 4, 2012 at 8:38 PM, .SuPaH sPii <
reply@reply.github.com

> wrote:
> 
> @Fogest If that's the case, i'll make it so whatever they're hitting
> something, it'll check it just like the chest cheat.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/h31ix/AntiCheat/issues/26#issuecomment-6115133

## 

~ Justin

**Comment by gravitylow** [comment]
Just to update you, @SuperSpyTX is working really hard on this, if you check out our development branch (https://github.com/h31ix/AntiCheat/commits/development) you can see the progress. We'll let you know when we have a stable version to push into a dev build.

**Comment by Fogest** [comment]
Awesome!

On Tue, Jun 5, 2012 at 10:51 PM, H31IX <
reply@reply.github.com

> wrote:
> 
> Just to update you, @SuperSpyTX is working really hard on this, if you
> check out our development branch (
> https://github.com/h31ix/AntiCheat/commits/development) you can see the
> progress. We'll let you know when we have a stable version to push into a
> dev build.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/h31ix/AntiCheat/issues/26#issuecomment-6141970

## 

~ Justin

**Comment by SuperSpyTX** [comment]
Also to update, this check will now cover anything interactable, including doors, buttons, levers, etc.

I don't have ALL the interactable blocks though, so if you know of one, let me know.

**Comment by Fogest** [comment]
Well blocks such as obsidian would be nice, considering glitching is big on
faction server which most bases use obsidian anyway.

On Tue, Jun 5, 2012 at 10:57 PM, .SuPaH sPii <
reply@reply.github.com

> wrote:
> 
> Also to update, this check will now cover anything interactable, including
> doors, buttons, levers, etc.
> 
> I don't have ALL the interactable blocks though, so if you know of one,
> let me know.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/h31ix/AntiCheat/issues/26#issuecomment-6142019

## 

~ Justin

**Comment by SuperSpyTX** [comment]
@Fogest what does obsidian do when I right click on it?  Nothing?  That isn't an interactable block..........

**Comment by Fogest** [comment]
Well then what I'm essentially saying is, will people still be able to use
freecam to break blocks and glitch through things?

On Tue, Jun 5, 2012 at 11:00 PM, .SuPaH sPii <
reply@reply.github.com

> wrote:
> 
> @Fogest what does obsidian do when I right click on it?  Nothing?  That
> isn't an interactable block..........
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/h31ix/AntiCheat/issues/26#issuecomment-6142045

## 

~ Justin

**Comment by SuperSpyTX** [comment]
@Fogest yes, they will still be able to break through things (currently).  After @h31ix tested it, I think there's still more work that can be done.  So it's quite not the final decision anyways.

**Comment by SuperSpyTX** [comment]
Update: This will not be implemented in the next update, but in the following due to work necessary.

**Comment by Fogest** [comment]
Well hopefully you do manage to get it updated soon. This actually is quite a game ruining cheat.

**Comment by gravitylow** [comment]
Fixed here: http://ci.h31ix.net/job/AntiCheat/191/
We plan on expanding this check too, so keep an eye out.
