### ISSUE TITLE
Server occassionally hangs when a player is kicked for spam.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#260]
Using the 1.6.2 build for 1.7.4 sometimes causes the main server thread to hang when kicking someone for spam.

**Comment by gravitylow** [comment]
Could you give me the output of /anticheat debug please?
Does this happen with all kicks or just specifically spam?

**Comment by ghost** [comment]
No debug output. I thought it was another plugin but this has happened like 3 times today RIGHT after someone is kicked for spam. Is there a way to enable a verbose debugging mode?

**Comment by gravitylow** [comment]
What do you mean there's no debug output? I just need the pastebin link that it gives you from that command. Please read: https://github.com/gravitylow/AntiCheat#bug-reportingsupportquestions

You can set the log level to the highest option (3) in the configuration to get more logs. I don't think there will be anything that relates to the cause, however. If you can confirm that this is ONLY after a spam kick and not for any others, that would be very helpful to me in finding the issue.

**Comment by ghost** [comment]
My bad, I was tired.

Here's the pastebin:
http://pastebin.com/jc6SPNk0

I can't do it after someone is kicked for spamming, I have to forcefully shutdown my server.

**Comment by gravitylow** [comment]
Again, can you please confirm that this is only after someone is kicked for spam, and not for other things (anticheat related or not)

**Comment by gravitylow** [comment]
@Mr-Burkes waiting on the above before I can continue.

**Comment by gravitylow** [comment]
@Mr-Burkes still waiting on the above before I can continue.
