### ISSUE TITLE
Does not work with Lift plugin

### ISSUE THREAD

**Issue by OriginalMadman** [gravitylow/AntiCheat#263]
It would be nice if ascension and flying checks could be disabled for when an elevator is in use (we have a ton of these on the server):

http://dev.bukkit.org/bukkit-plugins/lift/

**Comment by gravitylow** [comment]
The plugin would need to implement our API to accomplish this. I have no way of detecting this internally, and if I did it for all plugins it would be too crazy for me to manage. That's why we have the API :)
