### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by jleeevinnn** [gravitylow/AntiCheat#265]
Hey, first of all; just switched off NoCheatPlus and am using Enterprise. Liking it a lot, just encountering some minor bugs that should hopefully be easy fixes.
#1: /anticheat calibrate; I can successfully pass Step 1 and 2, however on step 3, it freezes.
#2: Giving a player 'anticheat.system.xray' permission node yields the player getting an error message when attempting '/anticheat xray <user>' "Insufficient permissions <anticheat.system.update>.

Yes, update, instead of xray, and I have to actually give them the update node for it to work.

**Comment by gravitylow** [comment]
Bug #2 has been fixed in version 2.0.1

The calibration system isn't implemented yet, which is why it isn't on the command menu yet. 

Thanks for the report :)
