### ISSUE TITLE
Command spam

### ISSUE THREAD

**Issue by csminecraft** [gravitylow/AntiCheat#268]
Using the reference located at http://gravitydevelopment.net/docs/anticheat/net/gravitydevelopment/anticheat/config/files/Magic.html it shows command_min and command_repeat_min values would increase leniency if you increase the values. This is incorrect and should show +leniency=decrease. I'm assuming it is a time reference and makes sense to decrease to add leniency. I have adjusted my magic.yml file with a lower value and works as expected.

**Comment by gravitylow** [comment]
Fixed, thanks!
