### ISSUE TITLE
Eggs thrown are not blocked

### ISSUE THREAD

**Issue by Xarias09** [gravitylow/AntiCheat#27]
Then.. I with my friend and cheaters from nodus IRC check this anti-cheat:

() Bukkit R3.0
() AntiCheat v.1.2.1 (Newest development build)

AntiCheat v.1.2.1 (newest dev) dont block:
() Freecam
() Unpushable
() Don't roll back completly destroyed/placed blocks (Problems with FastBreak/FastPlace)
() Bow Aimbot

FastPlace + Eggs -> cause this:
http://i.imgur.com/LnO1A.png

:)

**Comment by SuperSpyTX** [comment]
Updated issue title.

I'll investigate, or maybe @h31ix will.

**Comment by gravitylow** [comment]
Should be fixed here: http://ci.h31ix.net/job/AntiCheat/148/ (let us know if it is)

**Comment by Xarias09** [comment]
Fail title :S, this is not only egg thrown -_-, ill check it later

**Comment by SuperSpyTX** [comment]
@Xarias09 Well if there's another issue, make another issue.  We don't like issues with multiple problems on one.
