### ISSUE TITLE
AntiCheat spam permission not included in plugin.yml

### ISSUE THREAD

**Issue by timbru31** [gravitylow/AntiCheat#271]
Hey there,

just discovered that the new PERMISSION_SPAM https://github.com/gravitylow/AntiCheat/blob/master/src/main/java/net/gravitydevelopment/anticheat/util/Permission.java#L69

is not included in the plugin.yml anticheat.exempt section.

I believe it should be added or stated on the BukkitDev page that the spam permission is not part of this!

Cheers

**Comment by gravitylow** [comment]
Fixed
