### ISSUE TITLE
More False positives debug lncluded please advise

### ISSUE THREAD

**Issue by bradgillap** [gravitylow/AntiCheat#275]
http://pastebin.com/nWhau2QD

Please advise I really like this plugin.

**Comment by bradgillap** [comment]
Okay so the
bradgillap tried to break a block of LOG after only 0 punches (min=5)

This is from another plugin I have called craftbook. There is an option for "lopper" which breaks the entire tree. So that makes sense. 

I'm still working on understanding the others.

**Comment by gravitylow** [comment]
I need some context if you want help with these. Debug reports are designed to give me the technical information to help you if you present me with a given scenario that causes a false-positive to occur. Without that I can't do anything.

**Comment by bradgillap** [comment]
It's a big olle linux box. Which debug reports would that be. I already posted the debug from anticheat.

**Comment by gravitylow** [comment]
What I mean is you've given me the debug report but you haven't given me any context to the issue at hand. I have no idea what you need fixed.

**Comment by bradgillap** [comment]
No, it's all good now it seems. I'll close the ticket. Thanks for your help.

**Comment by DarkArc** [comment]
This was likely caused by: https://github.com/sk89q/craftbook/blob/master/src/main/java/com/sk89q/craftbook/util/ProtectionUtil.java#L52.

I'll take care of it.

**Comment by DarkArc** [comment]
Should be fixed after https://github.com/sk89q/craftbook/commit/d8c993112e7dd3d1ed457b4fa80dd9c7e0396a97 is finished up.
