### ISSUE TITLE
Error message in console

### ISSUE THREAD

**Issue by michielha** [gravitylow/AntiCheat#276]
Hi,

im getting a lot of error messages in my log, gameplay seems not to be affected. However my logs are extremely bloated by these messages. Something must be wrong. Im using 'vanilla' Spigot with anticheat as the only plugin. I've provided a screenshot of the error message with stacktrace. If any additional information is needed i may be able to provide it.

![screenshot 2014-02-16 17 23 26](https://f.cloud.github.com/assets/728995/2180649/b36d7250-9727-11e3-8c75-d354344439ba.png)

**Comment by DarkArc** [comment]
Update Craftbukkit

**Comment by michielha** [comment]
What do you mean by that. I run Spigot.

**Comment by DarkArc** [comment]
Well then get a newer version of Spigot. The API it's trying to use is not provided by your version of Spigot. You need a newer build.

**Comment by michielha** [comment]
Ah, thank you, I will update.

Date: Sun, 16 Feb 2014 11:10:21 -0800
