### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#280]
I don't know if i have done something wrong but i just installed this and i get an error there is so big that i can't view the whole thing in my console. http://pastebin.com/vuJ6m3Sd. I think it might be the http://dev.bukkit.org/bukkit-plugins/holographic-displays/ plugin that does something but i'm not sure.
and none of the anticheats work when i hack on my own server.

**Comment by ghost** [comment]
I would highly reccomend that you uninstall this plugin from your server. It does not protect you from 75% of the attaks. You should switch to NoCheatPlus, which requires a little bit more configuration but will never let you down.

In case you are advanced with Minecraft Hack Clients:
The Gemini and Almost All The Other Hack Clients Except Huzuni And Some More Work

**Comment by DarkArc** [comment]
Not true, one aspect of the Gemini hack client works -- the nuker.

**Comment by DarkArc** [comment]
You need to update CraftBukkit @ThatExGuy :)

**Comment by ghost** [comment]
You might want to recheck that, DarkArc. Me and some friends today tested how well the Gemini hack client works on my server using AntiCheat. Everything worked. AntiCheat did not give a warning. I am using CraftBukkit 1.7.2-R0.2. Also, Essentials did not kick me out for flying. This plugin really needs a huge update to keep people from switching to NoCheatPlus. HUGE UPDATE.

**Comment by DarkArc** [comment]
Were any of you op or did any of you have the anticheat exempt permission(s)?

**Comment by ghost** [comment]
I got it to work thx

**Comment by ghost** [comment]
Nope. We all deopped ourselves and changed our rank to the lowest.
