### ISSUE TITLE
Players trigger FLY check when swimming in oil.

### ISSUE THREAD

**Issue by mblob** [gravitylow/AntiCheat#292]
Players trigger FLY check when swimming in oil. (Buidcraft Mod)
http://pastebin.com/JWipCpmY

I do imagine tht oil is not registered as a fluid. 

Would it be possible to set some customs BlockID in the config file to be treated as fluid by anticheat. This would be a great improvement for mod compatibility. 

A temporary workaround would greatly help.

**Comment by gravitylow** [comment]
AntiCheat doesn't support third party server mods as it depends only on the Bukkit API. If you'd like to modify it to respect some other API, you're free to do so. As you might know, block IDs are being deprecated in future updates and so I don't plan on using them.

If you'd like a temporary workaround, you may add FLY to the list of disabled checks in the config.
