### ISSUE TITLE
Players get kicked for flying while running up stairs 

### ISSUE THREAD

**Issue by carlschoeneich** [gravitylow/AntiCheat#294]
On my server players get kicked for flying by AntiCheat when they run up stairs.

**Comment by gravitylow** [comment]
This project was discontinued in 2014. If you'd like to fork the repo to fix this, feel free!

**Comment by milosonator** [comment]
Maybe.... you should put that in the readme.md and point people to a proper replacement.

**Comment by gravitylow** [comment]
It's on the top of the repository and the BukkitDev page was replaced with that message. As for a replacement I don't play Minecraft anymore so I'm not filled in on anything except NoCheatPlus (http://dev.bukkit.org/bukkit-plugins/nocheatplus/) which has been around since I started.
