### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by coco0325** [gravitylow/AntiCheat#296]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO org.bukkit.event.EventException
16.12 05:04:56 [Server] ERROR Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.5.4-ALPHA
16.12 05:04:56 [Server] INFO [@: The entity UUID provided is in an invalid format]
16.12 05:04:56 [Server] INFO [@: The entity UUID provided is in an invalid format]
16.12 05:04:56 [Server] INFO Caused by: java.lang.ClassCastException
16.12 05:04:56 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
16.12 05:04:56 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:56 [Server] INFO org.bukkit.event.EventException
16.12 05:04:56 [Server] ERROR Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.5.4-ALPHA
16.12 05:04:56 [Multicraft] Skipped 629 lines due to rate limit (30/s)
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO org.bukkit.event.EventException
16.12 05:04:55 [Server] ERROR Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.5.4-ALPHA
16.12 05:04:55 [Server] INFO Caused by: java.lang.ClassCastException
16.12 05:04:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
16.12 05:04:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:55 [Server] INFO org.bukkit.event.EventException
16.12 05:04:55 [Server] ERROR Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.5.4-ALPHA
16.12 05:04:55 [Server] INFO [@: The entity UUID provided is in an invalid format]
16.12 05:04:55 [Server] INFO [@: The entity UUID provided is in an invalid format]
16.12 05:04:55 [Multicraft] Skipped 521 lines due to rate limit (30/s)
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO org.bukkit.event.EventException
16.12 05:04:54 [Server] ERROR Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.5.4-ALPHA
16.12 05:04:54 [Server] INFO [@: The entity UUID provided is in an invalid format]
16.12 05:04:54 [Server] INFO [@: The entity UUID provided is in an invalid format]
16.12 05:04:54 [Server] INFO Caused by: java.lang.ClassCastException
16.12 05:04:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
16.12 05:04:54 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-20161109a.jar:git-Spigot-de459a2-51263e9]
16.12 05:04:54 [Server] INFO org.bukkit.event.EventException
16.12 05:04:54 [Server] ERROR Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.5.4-ALPHA

I think something wrong. Can you help me?

**Comment by gravitylow** [comment]
Hey there, the plugin you're running is not AntiCheat (as it's been discontinued). You're using AntiCheatReloaded, and you should contact its author for support: https://www.spigotmc.org/resources/anticheatreloaded.23799/
