### ISSUE TITLE
slabs teleporting users down

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#30]
trying to walk off slabs in midair teleports a player down, even if sneaking

**Comment by SuperSpyTX** [comment]
Confirmed.  I'll be working on this.

**Comment by gravitylow** [comment]
Hm, I just tested this and it's really weird because it's not giving any kinds of logs at all, is that happening for you as well?

**Comment by gravitylow** [comment]
Please confirm the issue is fixed: http://ci.h31ix.net/job/AntiCheat/160/

**Comment by gravitylow** [comment]
Assuming fixed after testing.
