### ISSUE TITLE
Too laggy

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#31]
I've decided that while you guys are still figuring things out, I'm going to have to go back to using NoCheat temporarily. I like AntiCheat but it still needs a lot to be up to par. I know that NoCheat is outdated and will mean more work for me and my admins, however I cannot have a laggy server whatsoever. http://www.mediafire.com/?hp2jfzctp6ce01j (nolagg report)

**Comment by gravitylow** [comment]
I won't go and blame it all on you, but I have legitimately never heard a single person complain about AntiCheat lagging their server, and the general consensus seems to be that it is much lighter and NoCheat/NC+.

**Comment by Murabitos** [comment]
It only seems to be doing it when it's full at 50/50.. It can hold 75 but I keep it at 50. I think what's happening is that when there's not an admin online, hackers keep hacking sending off so many notifications that it lags the server. When the server lags it creates more false positives and then creates a snowball effect, see what I mean?

**Comment by gravitylow** [comment]
And it doesn't happen when AntiCheat is not on the server? Can you paste some logs?

**Comment by Murabitos** [comment]
Well I showed you the logs of the tickrate using nolagg. I know that Super has a program to read that file because I was talking to him. When the server is full again I'll have it run again and you can compare NoCheat and AntiCheat.. I really wish the NoCheat plus guy didn't quit updating his plugin, it was so safe and sound. :/

**Comment by Murabitos** [comment]
Here is the nolagg file of when NoCheat was installed: http://www.mediafire.com/?s1wm23te2842osf

(Once again super said he has the program to view it, it's a really really helpful program)

**Comment by SuperSpyTX** [comment]
After looking at the file, it appears that the PlayerAnimationEvent and PlayerMoveEvent are causing lag for your server.

Maybe @h31ix we can work on these events and making them as efficient as possible.

**Comment by gravitylow** [comment]
You said something about a "snowball" effect and false positives showing up. I would still like you to paste the logs you have from AntiCheat so I can see that.

**Comment by Murabitos** [comment]
here ya go http://www.mediafire.com/?vk3ww47abjtcedb

**Comment by gravitylow** [comment]
Alright, I think we'll definitly take a look into the issue and see if we can find similar setups that are having the same issue, however "Too Laggy" is too vauge of an issue to have in the tracker, so I think I'm going to close this and if you find a specific issue you can feel free to open one. Again, I'm not disregarding this, it will certainly be looked into. Sound ok?

**Comment by Murabitos** [comment]
Yeah sounds okay.. I hope your plugin or another can live up to the bar that the original NoCheat did..
