### ISSUE TITLE
Sprint Hack

### ISSUE THREAD

**Issue by Fogest** [gravitylow/AntiCheat#33]
A user goes faster then a person with speed 2 using this hack. I guess to fix it you basically just need to check if they have a speed 2 and if not they logically they should not be going that fast.

**Comment by SuperSpyTX** [comment]
Letting @h31ix handle this one.

**Comment by Fogest** [comment]
I probably could implement it myself though, I'd first have to understand
how your code worked. I have not learnt enough in Java quite yet to totally
understand others code.

On Mon, Jun 4, 2012 at 10:13 PM, .SuPaH sPii <
reply@reply.github.com

> wrote:
> 
> Letting @h31ix handle this one.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/h31ix/AntiCheat/issues/33#issuecomment-6116176

## 

~ Justin

**Comment by gravitylow** [comment]
What do you mean by speed 2? You mean the potion? 

So.... there's a speedhack that is not getting detected, essentially.

**Comment by Fogest** [comment]
Yes I mean the speed 2 potion. In particular I tried it using the Nodus
client and I was able to use the sprint hack feature fine on a server using
NoCheatPlus

On Mon, Jun 4, 2012 at 10:49 PM, H31IX <
reply@reply.github.com

> wrote:
> 
> What do you mean by speed 2? You mean the potion?
> 
> So.... there's a speedhack that is not getting detected, essentially.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/h31ix/AntiCheat/issues/33#issuecomment-6116535

## 

~ Justin

**Comment by gravitylow** [comment]
Wait wait. NoCheatPlus? Do you mean NC+ properly blocked it or didn't block it? And you're aware that you are making a bug report for AntiCheat not NC+ right?

**Comment by Fogest** [comment]
Crap, I got confused between the two. Looks like I've just made a big mistake lol.
