### ISSUE TITLE
Anticheat false alarm

### ISSUE THREAD

**Issue by Kaos1337** [gravitylow/AntiCheat#34]
Hi,
I use anticheat v1.2.1 and cb #2203
My users have problems with this plugins, since the last version when one of them is under the water and try to go up he is kicked by the anticheat, or when they eat chicken the heal return to 0 and the anticheat kick them for cheating.
What can I do?

**Comment by SuperSpyTX** [comment]
Sounds like an outdated build.  Can you please try a devbuild at http://ci.h31ix.net/

And give AC logs along with it.

**Comment by Kaos1337** [comment]
Ok, I've just downloaded the build #151

**Comment by SuperSpyTX** [comment]
No AC logs?

**Comment by Kaos1337** [comment]
Ah sorry, I missed it, this is my log file: http://www.mediafire.com/view/?ua8opfqsdar8z14 but I think that I have to activate something....
This is my config file: http://pastebin.com/aps7FatY

**Comment by SuperSpyTX** [comment]
Let's start by resetting your AC configuration and trying to replicate these issues again.

Bring back the logs when you can.

**Comment by gravitylow** [comment]
Also, set file logging to true in the config, please.

**Comment by SuperSpyTX** [comment]
First issue should be fixed in http://ci.h31ix.net/job/AntiCheat/158/
