### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by diablo10001** [gravitylow/AntiCheat#35]
I was playing in my server just walking around and nothing seemed wrong but i just clicked my cmd to see if any errors and there was one and it kept spamming it, i updated to newest build but it kept saying this:

at net.h31ix.anticheat.util.Utilities.isUsingMcMMOAbility(Utilities.java:101)
at net.h31ix.anticheat.manage.Backend.checkLongReachBlock(Backend.java:145)
at net.h31ix.anticheat.event.PlayerListener.onPlayerInteract(PlayerListener.java:130)

**Comment by SuperSpyTX** [comment]
You basically cut the essential part of the log.

Send us full logs.  Including the "Exception occured".   I would go find the exception in server.log file.

**Comment by diablo10001** [comment]
well i figured out the issue, i had a not up to date mcMMO, sorry for the ticket but i couldn't find anyone else with this problem, also if you still need to error messages i cant get it because i don't receive it, but yea sorry

**Comment by SuperSpyTX** [comment]
That's fine.   That should've been the first thing I asked.
