### ISSUE TITLE
Giga Drill Breaker causes false positives

### ISSUE THREAD

**Issue by TheFarmerNL** [gravitylow/AntiCheat#36]
I really want this plugin to run on our servers, since it detects a lot more than nocheatplus, but the problem is that we are using mcMMO abilities and anticheat thinks when a player is using an ability, he is hacking and kicks him.

Versions:
AntiCheat v1.3-DEV-b153
Craftbukkit #2206

Player who got kicked said:
"I used giga drill and it said hacks are not allowed in this serve"

I had disabled the plugin immediately afterwards, but i would be glad to run it again in a more detailed mode if it helps.

Can you insert mcmmo abilities into AntiCheat?

Regards,
TheFarmerNL

**Comment by SuperSpyTX** [comment]
Not enough information.  McMMO abilities are built into AntiCheat.

Please provide logs.  And what exactly? giga drill?

**Comment by SuperSpyTX** [comment]
Fixed in devbuild http://ci.h31ix.net/job/AntiCheat/155/

EDIT: Updated issue title to better reflect issue.
