### ISSUE TITLE
TnT explosions buggy and tp you to the ground

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#37]
When you are next to tnt it should launch you in air.
But instead you go in air and get tped down for flying/moving.

**Comment by SuperSpyTX** [comment]
Finally, I can confirm this because mass slapping everybody with CommandBook can also throw a false positive.

I will fix this one later.

**Comment by SuperSpyTX** [comment]
http://ci.h31ix.net/job/AntiCheat/164/  - Test if this fixes your problem.

My issue with CommandBook is now resolved.

**Comment by SuperSpyTX** [comment]
Ok i just did this like what, 3 times.  I've updated both my comments with the build you SHOULD be using now.

**Comment by SuperSpyTX** [comment]
I'll go ahead and close this issue, if you still have problems, feel free to reply.
