### ISSUE TITLE
You can fly straight up with low speed and stay in air.

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#38]
I just checked it with nodus to fly slowly up and it's not giving any messages in console and i could stay in air for hours.
When moving in any directions it glitched and gave warnings but straight up works.

**Comment by SuperSpyTX** [comment]
Now this is completely bs because the Y-axis check is supposed to solve this.

Sounds completely outdated.

Logs?

**Comment by Rojoss** [comment]
http://www.youtube.com/watch?v=LpO-XHy_dck

Here you can clearly see i'm flying on another account in the default group that don't have any AntiCheat permissions.
And there is nothing in logs only when you go down then it say xx tried to avoid falldamage.

**Comment by gravitylow** [comment]
The flying straight up issue does in fact exist on speed 1.0, however flying forwards works as expected.

**Comment by Rojoss** [comment]
Yeah the forward is getting blocked fine.
But players can just go up and get in sky bases now.

**Comment by SuperSpyTX** [comment]
This issue can be fixed.  But I can't do it right now.

H31IX can though.

**Comment by gravitylow** [comment]
I'll be looking at it. Don't worry though, you're right but up until this point when something changed it's been working fine, so that's why he had that reaction. That won't happen again.

**Comment by gravitylow** [comment]
Fixed here: http://ci.h31ix.net/job/AntiCheat/160/ , please reply and confirm that it is fixed.

**Comment by gravitylow** [comment]
Assuming fixed.
