### ISSUE TITLE
Lumberjack

### ISSUE THREAD

**Issue by Cheesemantice** [gravitylow/AntiCheat#39]
We have an issue. When players try to cu a tree thay kicked for hacking. We use Lumberjack. Latest version: http://www.almuramc.com/downloads.htm

**Comment by SuperSpyTX** [comment]
Please post either Console Logs or pictures/video evidence of this happening.

**Comment by gravitylow** [comment]
I replied to this comment on dbo: Tell the plugin author to use our [API](http://dev.bukkit.org/server-mods/anticheat/pages/api-documentation/) to make it compatible. You can tell him that if he has a public github repo, we can help him implement it, or if he needs technical information he can PM use for the rundown.
