### ISSUE TITLE
Delay for Log.

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#4]
It would be great if there could be a delay for the log configurable.
With like 100/200 players online the log is growing really really fast and i don't wanna have to clear it every day.
So i think it would be a great idea to have a configurable delay for the messages reported tot he log.
In ticks or seconds or whatever that doesn't really matter but it's just annoying that the log is getting extremely big.

**Comment by gravitylow** [comment]
Would an option to turn off file logging work? It doesn't sound like you are really using it.

**Comment by Rojoss** [comment]
There is already a option for that..?
And i'm using the logs when players get reported i want to be able to check back if someone did.
And spamming 100 lines in the log for 1 action is really to much

**Comment by gravitylow** [comment]
What do you mean 100 lines for 1 action? In the file logs, there is only 2 lines/warning

Also, no, there is an option for _console_ logging, not file logging.

**Comment by Rojoss** [comment]
Well if someone is trying to speed hack and continue it easy write like 100 lines.

**Comment by gravitylow** [comment]
How about this, I'll add a setting for file logging, you will be able to set a number (0-3) or something on how detailed the log should be. 0 is off, 1 just writes something every time action is taken on someone, 2 is a little more detailed, and 3 is everything. Does that sound ok?

**Comment by Rojoss** [comment]
Yeah sure :)

**Comment by gravitylow** [comment]
Fixed as of http://ci.h31ix.net/job/AntiCheat/116/
