### ISSUE TITLE
Any attempt to eat results in "* tried eating too fast"

### ISSUE THREAD

**Issue by ttk2** [gravitylow/AntiCheat#43]
We are running the latest stable build of [Bukkit++](http://forums.spout.org/threads/craftbukkit.938/) and a few minutes after restarting the server with Anticheat installed it began reporting that nearly everyone was eating too fast. There where 37 players online and a tick of 12 or so. To players it looked like they ate some food and their hunger bar was unaffected.

**Comment by gravitylow** [comment]
We do not support unofficial builds of craftbukkit/bukkit (like CB++), as they cause issues that are not present in official builds. Please change to an official build.

**Comment by ttk2** [comment]
Not an option, bukkit just can't reasonably handle 100+ people. Regardless of that, I understand not supporting alternate builds, but the plugin support has so far been impeccable and the nature of the error itself leads me to think it may be related more to the tick rate than cb++. Regardless, otherwise great plugin, keep up the good work.

**Comment by gravitylow** [comment]
This is totally opinionated, but almost every time I see someone having these outlandish issues that have not been seen in other version of Bukkit, it is typically always CB++ users. The fact that they are not updated in time due to the author's refusal to do so makes it very difficult to provide support, and a lot of times we try to help people using these versions of CB without knowing it, and later they mention it to us after hours of debugging which solves the issue.

I personally have no issues with the team that makes CB++, I just think that the way they go about it is unhelpful to developers. Also, I have seen 100+ slot servers running Bukkit just fine. I think CB makes users have more issues than it actually solves with efficiency or anything else.

**Comment by ttk2** [comment]
The optimizations in CB++ heavily favor a very specific set of server conditions, large numbers of spread out users on a large map. If you have all of your users in one spot, or close enough that their view distances regularly overlap you will never be able to tell the difference performance wise from CB++ and regular CB, its when you get into situations with tens of thousands of loaded chunks that you start to see performance increases. That being said I have not tried regular CB and performance compared the two for a few MC revisions I think I will do that soon. 

I totally support your decision not to work on CB++ issues, my server has 5 or so custom plugins and its a nightmarish job debug them when we have total control over the situation, I can just imagine trying to do debugging from your position. Thanks for the work regardless!

**Comment by ttk2** [comment]
Vindication! Just switched to regular CB to try it out again, eating problem is still there. Jury is still out on lag improvements though.

**Comment by ttk2** [comment]
Jury is in, tick with 37 players regular bukkit 7, tick with cb++ and 40 players (same situation, initial reconnect after restart) is 20, all else equal. Thanks for making me check out regular bukkit again though, its nice to see that everything still works for when we switch back after 1.4 (that is if Afortress does not go through with his totally recoded open source client) 

So, back to the subject at hand, the issue is still apparent in regular CB and i think its related to low tick rate. As the player is "eating too fast", the player eats at normal speed, but the server with a low tick rate thinks the events are happening faster than they really are and flags the player. In some of our custom mods we have to go get system time instead of using tick for time because of this.

**Comment by gravitylow** [comment]
If it was in issue related to Bukkit or Bukkit's tick rate, it would be a much more widespread issue. I have not received any complaints about this except from you. I'm not ruling it out, but you can't act like it's an issue with a 20 tick server and with a 7 tick server.

I have also asked a few other server admins who run AntiCheat and support the project if they have noticed anything like this, they all responded no.

**Comment by ttk2** [comment]
Oh, sorry, my wording must have been confusing. When I returned to bukkit++ I also unloaded anticheat as the tick of 20 with 30-40 is pretty normal, but as people start girding and more people join (at 70 or so now) the tick falls again, which is what inspired the issue the first time when I ran anticheat on bukkit++. So, to make it clear I did not see issues on either bukkit build unless the tick was below 15 or so, which does happen on both although it does seem CB++ preforms better. 

It also explains why I did not see any problems when running it on my test server as it has a perfect 20 tick since almost no one is online there. 

Sorry for the confusion.

**Comment by gravitylow** [comment]
Ok, so this should stay closed? I can look into the tick issue, but as far as I can tell that's more of another issue to be looked at rather than a bug in AntiCheat.

**Comment by ttk2** [comment]
Hmm, that's really up to your discretion, the error is reproducible in both versions and only seems to manifest when the tick becomes rather low. It could be related to one of our custom plugins or any one of a million other issues but I don't think it is. We have been using NoCheat and now NoCheatPlus and both have similar issues, when the tick is low all of the "doing x too fast" errors become quite prevalent, but since NoCheat does not seem to stop the hunger boost when the 'eating too fast' flag is thrown its worked ok for us. I would love to be able to use your plugin as from my experience with it on my testing server (with a high tick) it seems far superior to NCP and I think that overall you will get more accurate cheating detection if you switch to using system time instead of tick even if this particular issue is caused by some unknown factor.

**Comment by gravitylow** [comment]
Yeah, I hear your issues, it's just the fact that in none of the servers I have tried this on (I went and tried the mcMMO server too, which has 100 slots, and eating is working fine) has this issue been out there. It sounds like something is causing the tick to go down on your server that isn't in all the others. I'm glad you're liking AntiCheat, and I can certainly look and see if there's anything we can do to prevent more laggy servers from getting affected by checks like this, but it's hard to cater towards a very specific setup and server, especially when the vast majority of ones like it do not have the issue.

**Comment by ttk2** [comment]
The tick issue has been discussed and after some research I have come to the conclusion that there is a specific piece of hardware common in server builds that seriously decreases Minecraft server performance, I have been trying to narrow it down and i think its ECC RAM, I am working on moving to another server machine soon enough, you think we could get enough money for that in a community of 1,100, but so far no. Anyways, enough about my problem, no need to pander to me, I just wanted to inform you, if I really needed this to work I would just get my programming team to make whatever changes where needed. 

That being said, I don't think it needs to be an issue, but using the system clock would make the plugin in general more accurate and may be worth it if you have the time someday.

**Comment by gravitylow** [comment]
Sounds good.

**Comment by GravelSocks** [comment]
@ttk2: Why not take out all plugins except AntiCheat and see if the problem still occurs on regular CB.  If not, then add them back one at a time until it does.
