### ISSUE TITLE
Incorrect Fly Hacking Warnings with Normal Mine Cart Movement

### ISSUE THREAD

**Issue by GravelSocks** [gravitylow/AntiCheat#44]
AntiCheat throws "Fly hacking on the y-axis" warnings when players are ascending in mine carts on redstone-powered track (for example in a tight spiral).

<<code lua>>
[AntiCheat] Fly hacking on the y-axis detected.  Please wait 5 seconds to prevent getting damage.
(repeated 8 times)
<</code>>

I have also seen "Fly hacking" or "Moved too quickly" warnings when players are un-flying normally by double-tapping the space bar and falling to earth in creative mode...upon landing maybe.

It looks like besides just movement rate, you also need to check player status.  For example, it should probably never warn when a player is in a minecart, since they are not in control of their movement, nor should it warn if they have turned off flying.

**Comment by gravitylow** [comment]
Should be fixed here: http://ci.h31ix.net/job/AntiCheat/165/ please reply and confirm.

As for the exit flying issue, this is a known problem for which I have a fix, but first I need these two commits to be pulled:
https://github.com/Bukkit/CraftBukkit/pull/779
https://github.com/Bukkit/Bukkit/pull/610

I have already spoken multiple times to the Bukkit team about the need for this event, which will help me solve this issue, and it seems like it's good to go, but currently all new features are being held off until a few very problematic issues are fixed and some new builds are available that have that fix. At that point, pull requests and the developer's new additions will start being pulled again. 

If you would like to help with that, you might want to comment on the pull requests saying something to the extent of "+1, this is needed for fixing fly detection bugs within plugins" or something, to show them there is an active need for this, which I can't do by myself just by talking to them.

**Comment by GravelSocks** [comment]
Yes - the minecart problem is now fixed in the instance of the problem I saw.  Thanks for the rapid turn-around!  I commented on both threads.   The "unflying" problem is not as bad, since it only resorts in a few warnings that do not trigger a critical threshold.   However, you may also want to consider config options that let users set the detection thresholds for change in rate and number of events per warning category, etc.  It adds some complexity, but also gives operators extra control.    I've also looked at the permissions, and I see an "exempt" node, but I don't see an "enforce" node, which would just ignore the client and just not let players do things they shouldn't - maybe that is the default mode when you don't specifically detect a hacked client.   Alternately, you could also have an "add-on" list in the config for extra client/hack identifiers to block (to avoid the scenario of being broken by every new hack that appears), but that would assume that all hacks report themselves or clients on the minecraft/mojang side had some kind of client-server runtime verification for modification based on build checksums or some other mechanism.

**Comment by gravitylow** [comment]
I don't really want to go the NoCheat route; it's confusing, overwhelming, and the vast majority of people I know praise AntiCheat because it just... works! No need to go through and setup every single value. I would like to do some things to allow more control over the system, but I don't think just allowing players to get dirty with all the magic numbers is a great idea.

AntiCheat by default enforces the rules on players, if you give them the exempt node it will totally ignore them and never check them for anything. 

I'll close this now, thanks for confirming.
