### ISSUE TITLE
Newest Dev AntiCheat# Command spam

### ISSUE THREAD

**Issue by Xarias09** [gravitylow/AntiCheat#45]
Hi!,

At newest version o AntiCheat command spam is too sensitive..
Maybe add feature to disable it?

Greetings

**Comment by gravitylow** [comment]
Hi, I just tested this by going through help pages over and over again. I was not able to trigger any spam warnings. The only thin that did trigger spam warnings is when I tried to issue the same exact command 2-3 times in a row, in which case it will ask you to stop spamming.

However, I think an option for this would be good, I'll add it.

**Comment by gravitylow** [comment]
This build has the update: http://ci.h31ix.net/job/AntiCheat/166/

**Comment by GravelSocks** [comment]
Well...I don't know that a simple disable is the best fix.  It is the quickest fix, however.   A better system is one where you distinguish between obnoxious player chat flood vs. legitimate command use and provide thresholds for the commands as I suggested in the newer bug.   But, glad there is a near-term work-around.

**Comment by gravitylow** [comment]
You can always give players the anticheat.spam permission node and it will ignore them, but AntiCheat isn't reaallyy a spam prevention system, if you want a plugin that is dedicated to doing that I would suggest checking out AntiBot.

**Comment by GravelSocks** [comment]
I tried out the latest build with chat spam set to true and command spam set to false and it works OK.    I suppose there are a lot of gray areas in command spam, but just turning off the screening is probably the best option vs. trying to handle all the gray cases without a dedicated command:threshold architecture.   Preventing chat spam is good.  There's no reason to repeat chat messages.   Anyway - the major issue of blocking normal command use is resovled.  Thx.  I have been trying to identify any bugs that prevent normal creative/survival use with unhacked/vanilla clients.   So far, so good - just the digging bug.  I'm about to check super pick-axe.
