### ISSUE TITLE
User will be kicked

### ISSUE THREAD

**Issue by Spezialeinheit** [gravitylow/AntiCheat#46]
My users will be kicked out if they are frozen by a warning:

http://www.youtube.com/watch?v=sMS-ByLUwxE

**Comment by gravitylow** [comment]
Try this build here and see if it works any better: http://ci.h31ix.net/job/AntiCheat/167/

**Comment by Spezialeinheit** [comment]
I now have the warning plugin anticheat made ​​compatible :)

NoFall and Speed
