### ISSUE TITLE
Repeated inventory commands trigger spam warnings...

### ISSUE THREAD

**Issue by GravelSocks** [gravitylow/AntiCheat#49]
When repeating certain commands (give, /i, etc.), AntiCheat gives spam warnings.   For example, I was trying to fill a bank of dispensers and was issuing the command:  /i [item] 576.  After the 3rd time, I started getting spam warnings and the command didn't work, which was a pain.   I worked around the problem by changing the quantity, but I shouldn't have had to do that.

One way to fix this would be to provide a command list in the config that bypasses the AntiCheat parser.   There could be a basic set and server operators could add additional commands to the list, as needed.   Maybe there would also be a threshold parameter for the number of times you could use a certain command.  

For example:
# repeat an inventory command up to 10 times before triggering a spam warning

i:10
# repeat the spawnmob command 5 times before triggering a spam warning

spawnmob: 5
# never trigger on the give command (or override an AntiCheat built-in default threshold)

give:-1

These comments imply a slight architectural shift, but would make AntiCheat more flexible and customizable.  Maybe there are crossovers with plugins like Essentials, but since you are attempting to include flood/spam control, there needs to be additional intelligence, beyond simple string matching, which is triggered by detecting commands vs. regular text (leading "/" character).

**Comment by gravitylow** [comment]
Refer here: https://github.com/h31ix/AntiCheat/issues/45

You can also give yourself the anticheat.spam permission node and it will ignore you.
