### ISSUE TITLE
Fly mode bug

### ISSUE THREAD

**Issue by Kowagirl** [gravitylow/AntiCheat#5]
With fly mode enabled (essentials) A user can also speed fly with a client mod. I addressed this issue to Supahispii, and he sent me a test build, on which you could not fly fast anymore, yet it was turning up a false positive on regular fly mode, and glitching the user back.

**Comment by SuperSpyTX** [comment]
All I have to do is find the speed at which creative mode fly works at, and then when I do, i'll patch it up.

I'll be leaving this open for other ideas if H31IX bashes me on this one.

**Comment by gravitylow** [comment]
I've fixed this in http://ci.h31ix.net/job/AntiCheat/118/, using @SuperSpyTX's changes as a base. @Kowaman said that it was working ok now.
