### ISSUE TITLE
Using Shears causes escalation, and eventually kick.

### ISSUE THREAD

**Issue by MachEntertainment** [gravitylow/AntiCheat#50]
Some members of my server have been having issues when shearing leaves.  More specifically when they shear leaves in a continuous fashion it causes it an escalation and kick if they do not listen.  I will get more info to you when the member gets back on.
  As for the log, no errors posted, just "Kicked for hacking". Anti-cheat seems to be doing it's job right.  

Thanks for any help,
Alex J.

**Comment by gravitylow** [comment]
Are you using the latest dev build? I need to know what version you are using.

**Comment by MachEntertainment** [comment]
I'm running version V1.2.1, thanks also for the quick response.

**Comment by gravitylow** [comment]
Can you try the latest version (1.3) and tell me if it fixes the issue? It should have been downloaded to your server.

**Comment by MachEntertainment** [comment]
Alright downloaded the latest dev build. I have tried to replicate the issue and it appears solved, thanks! However with the new version (V 1.3.1-B172) and it seems the anti-spam is acting up.  Multiple users have been banned relatively quickly for "spamming" when they were only talking fast. I tried it myself and replicated the results.  It seems that it won't reset, or acts a little to fast.  Members aren't sure if they are allowed to talk yet and get banned.  Anyway to configure the actions taken for the different spam levels? I checked my config and events have been set to "kick" for "high"

Thanks for the help on the previous problem.

**Comment by gravitylow** [comment]
Try http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/

**Comment by MachEntertainment** [comment]
Thanks members don't seem to getting banned anymore.
As a matter of fact, spamming doesn't seem to be getting picked up, but I'll cross that bridge if it comes to it.

**Comment by gravitylow** [comment]
Ok :p the spam seems to be getting picked up but if it doesn't for you just open an issue for it.
