### ISSUE TITLE
Spamming bug

### ISSUE THREAD

**Issue by xdeathoreox** [gravitylow/AntiCheat#51]
On a server, anticheat is installed. Nothing is done with the config. But people are randomly getting kicked for spaming. When they really aren't. Then, when they join again, if they say anything, it tells them to stop flooding the server, then kicks them. Join again, say anything, you get banned. 

PS: Sorry if this doesn't make sense. I'm tired and not really focusing on anything.

**Comment by gravitylow** [comment]
Are they issuing commands over and over again?

**Comment by gravitylow** [comment]
Check and see if this fixed it: http://ci.h31ix.net/job/AntiCheat/175/
