### ISSUE TITLE
Could not pass event PlayerInteractEvent to AntiCheat

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#52]
http://pastebin.com/B9HRYVTJ

I know this issue is with mcmmo. Anticheat works beautifully with mcmmo dev build #901, all dev builds after 901 from what I have tested, #902-907, give this error. Not sure if you can fix it on your end or not but I have contacted mcmmo to see if they can fix it because something changed in 902+ builds.

**Comment by gravitylow** [comment]
Hi, this was due to an API change we were not aware of in mcMMO. I'll be updated the dev builds to support this change.

**Comment by gravitylow** [comment]
Fixed here for mcMMO dev builds #902 and above: http://ci.h31ix.net/job/AntiCheat/178/
