### ISSUE TITLE
Chat Spam Detection Much Too Sensitive / Incorrect String Compares?

### ISSUE THREAD

**Issue by GravelSocks** [gravitylow/AntiCheat#53]
Players are being warned for chat spamming when they are aren't actually spamming.    There may be a bug in expression matching.   Having any normal conversation triggers escalation and they have to switch to private messaging to avoid being kicked.

**Comment by gravitylow** [comment]
Are you using 1.3.1?

**Comment by GravelSocks** [comment]
I just installed it - maybe this is a duplicate.   I reported prior to using 1.3.1.

**Comment by gravitylow** [comment]
Check it out and let us know - especially the latest dev build (181) should contain an even better fix for this.

**Comment by GravelSocks** [comment]
It has been a couple of days - no complaints so far.  Seems to be working OK!

**Comment by gravitylow** [comment]
Alrighty, thanks.
