### ISSUE TITLE
Commercial

### ISSUE THREAD

**Issue by SWBThorben24** [gravitylow/AntiCheat#54]
Hello,

we from MineTime.ME would like to knwo can we use the plugin?

Becuase our server is Commercial.

We need the permissions from you, that we are allowed to use the plugin,

greets

prhosting
Sponsoring

**Comment by gravitylow** [comment]
We don't care who uses the plugin - the [GPLv3](http://www.gnu.org/copyleft/gpl.html) (our license) outlines this.

**Comment by SWBThorben24** [comment]
Thank you very much. #closed
