### ISSUE TITLE
A problem with /spawn and McMMO

### ISSUE THREAD

**Issue by ImShady** [gravitylow/AntiCheat#6]
My Plugins (26):

Autosneak 
Minequery 
WorldEdit 
VoxelSniper 
BuyCraft
Vault
PermissionsEX 
CombatTag
WorldGuard 
MCDocs
 iConomy 
OpenInv
ScheduledAnnouncer 
NoCheat (temporarily since I experienced the bug with anticheat)
Votifier
 McMMO
LogOres 
Essentials (which is being used for /spawn)
WorldBorder
ServerSigns 
EssentialsSpawn 
VanishNoPacket
 LWC
EssentialChat 
Factions

The Bug:

Using beta build #113 as provided here, dev.bukkit.org/server-mods/anticheat/ (for the sake of McMMO), I experience a little bug where sometimes (not all the time), when players do /spawn, AntiCheat detects this as some form of Flying on the y Axis. I think that this might have to do with the fact that my spawn is floating in the air, and people are ported up. Just a possibility. Lastly, the tree feller ability in McMMO is still having a bit of problem, with AntiCheat detecting it as hacking as well. With all the other skills it's working fine. People have also experienced the Flying on the y axis problem when they /home into their base in the air. I am using EssentialSpawn to for /spawn management. If you have any other comments related to my plugins or anything else feel free to let me know.

Many Thanks,

Mentalist.

**Comment by gravitylow** [comment]
Fixed as of dev #121 http://ci.h31ix.net/job/AntiCheat/121/

**Comment by ImShady** [comment]
Users are still experiencing this issue, running build 121.
