### ISSUE TITLE
Massive spam on console and in-game due to visual checks.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#65]
Using anticheat #191-194, console and in-game reports keep massively spamming reports from 2 players due to the visual checks. I couldn't tolerate it any longer because it was about a hundred reports a minute. Downgraded to anticheat #190, everything is flawless.

**Comment by SuperSpyTX** [comment]
Update to build #194.  Problem solved.

http://ci.h31ix.net/job/AntiCheat/194/

**Comment by ghost** [comment]
I tried #194, it was spamming me.

**Comment by gravitylow** [comment]
Please paste the messages you were getting.

**Comment by SuperSpyTX** [comment]
This issue was misread.  For now, downgrade, and then continue this with issue #66.

Oh, and sorry for the mass open/closing.

**Comment by SuperSpyTX** [comment]
Please try build http://ci.h31ix.net/job/AntiCheat/195/ and report back results on issue #66
