### ISSUE TITLE
Pressure plate problems..

### ISSUE THREAD

**Issue by Jr123456** [gravitylow/AntiCheat#67]
Hi I just started using AntiCheat.. i got the latest build and all..everything is working fine...
but i have this 1 issue

Everytime i step on a pressure plate (Stone)
the anti-cheat detects something gives me a warning and kicks me right away

it gave the 
[ALERT] of medium hack level
then right away
another alert
[ALERT] high hack level

and it kicked me out
tried it quite a few times

So I put down a pressure plate test it by walki on it back and fort...
then that happens

**Comment by SuperSpyTX** [comment]
If we don't have the exact logs, we can't help you.

Provide the exact log you are getting.  Are we seeing a "player tried to interact with a object he couldn't see"?

**Comment by SuperSpyTX** [comment]
Ok you don't have to provide anything else.  I'm going to be working on this.
