### ISSUE TITLE
Jump potion causes hack accusations :)

### ISSUE THREAD

**Issue by zathrus-writer** [gravitylow/AntiCheat#68]
When players have jump potion effect on them and jump with it, they get teleported back to ground and are accused of hacking. I guess this problem would be with more potions that this, but I never had any other reports.

**Comment by SuperSpyTX** [comment]
Sounds like an outdated build.

Try atleast v1.3.1 of AntiCheat.

EDIT: I don't think it sounds outdated, I think it's just we never actually checked it.   I'll have @h31ix look into this.

**Comment by gravitylow** [comment]
I checked, Use the latest dev build.

**Comment by zathrus-writer** [comment]
sry for not including the version... I already am using 1.3.1 ... I'd rather wait for a release than using dev build - or are they considered stable for production use?

**Comment by gravitylow** [comment]
They are mostly all very stable. We encourage anyone having issues to use them.

**Comment by zathrus-writer** [comment]
it seems to work, thanks a lot!
