### ISSUE TITLE
Reorganize /anticheat report

### ISSUE THREAD

**Issue by SuperSpyTX** [gravitylow/AntiCheat#69]
We need to stop paginating and only show the values by the player that is >0.

EX: 
 --------------------[REPORT]---------------------
Player: SuperSpyTX
Level: Medium

**Comment by gravitylow** [comment]
I agree, the original version was done fairly quickly. Hopefully we have some time soon to make a really nice system for reports.

**Comment by SuperSpyTX** [comment]
Maybe if you don't work on this by the time i get back, I'll probably work on it.  It doesn't seem hard to do.
