### ISSUE TITLE
enderpearls

### ISSUE THREAD

**Issue by ryanogilvie** [gravitylow/AntiCheat#7]
Sometimes when players use enderpearls it will log them flying on the y axis. I have a couple people on my server who have had this issue with the plugin. Also when this happens sometimes the player gets stuck in a wall or somewhere maybe blocks below or a little around it from where they threw the pearl then it starts saying your flying again when you try to move sometimes.

**Comment by ImShady** [comment]
I second this issue.

**Comment by gravitylow** [comment]
Fixed as of dev #121 http://ci.h31ix.net/job/AntiCheat/121/
