### ISSUE TITLE
Players falling/jumping through vines triggers flying detection.

### ISSUE THREAD

**Issue by hakusaro** [gravitylow/AntiCheat#71]
I've got a treehouse on my server that, when you jump through and fall in and around hanging vines, trips the flying detection. As a result, you get teleported around randomly.

As a work around, I'm granting all players the ability to cheat using the flying permission, but keeping Minecraft's flying detection enabled.

Example vines:

![Example](http://puu.sh/AM7A.png)

**Comment by gravitylow** [comment]
This may be fixed in the newest build http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/ try it out.
