### ISSUE TITLE
Placing blocks near/in water.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#73]
I'm using anticheat #199 and the visual checks still seems a bit too spammy for users. I don't necessarily want to downgrade but I can't resorted to giving all groups a bypass for the visual check because I can't find a permission node for it. What exactly is the visual check for and why is it so sensitive?

**Comment by ghost** [comment]
Also to add, I've had some admins report users can't place items in water anymore or near water such as reeds. I've only started to hear about this issue once I updated anticheat.

**Comment by SuperSpyTX** [comment]
Are we seeing an issue with placing blocks (such as reeds) in the water or near it?

If so, i'm updating the issue title.

The permission node you (should give) is anticheat.check.visual

**Comment by gravitylow** [comment]
Confirmed. Looking into this now, it makes sense.

**Comment by gravitylow** [comment]
Try the latest build http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/

**Comment by ghost** [comment]
Seems to be working, no more complaints. Thanks.
