### ISSUE TITLE
Remove Coal Ore in X-Ray stats

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#74]
I've noticed that most of the xray reports I receive in-game are all from coal ore percentage. In my opinion, coal ore is a bit too common so the anti-cheat xray is a bit too sensitive. Would it be possible to remove or disable the checking of coal in a config file?

**Comment by gravitylow** [comment]
It's possible. We've received a few requests for this, so I might look into it.

**Comment by SuperSpyTX** [comment]
Updated issue title to better reflect the issue.

**Comment by ghost** [comment]
Coal has been removed with the newest build of anticheat.
