### ISSUE TITLE
Player tried to interact with an object that they couldn't see

### ISSUE THREAD

**Issue by Spezialeinheit** [gravitylow/AntiCheat#77]
2012-06-14 17:10:53 [INFO] [AntiCheat] player tried to interact with an object that they couldn't see

All my Users have that. Each block is affected. I have DEV: 198

**Comment by gravitylow** [comment]
Every block on the server? What are they doing, placing, breaking, or opening chests and stuff?

**Comment by Spezialeinheit** [comment]
Placing and Breaking

**Comment by gravitylow** [comment]
See if the latest build fixes the issue: http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/

**Comment by gravitylow** [comment]
We've decided to limit the visual check to only chests in preparation for 1.3.2 - we are planning to continue work on it after this build, that way it's not holding us up from a new version.

**Comment by SuperSpyTX** [comment]
This is now closed due to precedence of #80
