### ISSUE TITLE
Many errors lagging server out and spamming console.

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#79]
Here some part of the log
http://pastebin.com/6C76f3C5
Please look into it.
Used build 202 btw

**Comment by gravitylow** [comment]
Use the latest AntiCheat dev build and the lastest mcMMO dev build.

**Comment by Rojoss** [comment]
Alright thanks errors are gone.
Only other plugins are broken now that use mcmmo.
So i will just downgrade both again.
But thanks for the quick respond.
