### ISSUE TITLE
sprint jump+ sneak

### ISSUE THREAD

**Issue by ryanogilvie** [gravitylow/AntiCheat#8]
When you jump while sprinting and then press shift to sneak it always logs this as trying to sneak to fast.

edit: it also logs this when in creative mode and flying if you hit the ground while moving forward (not straight down) by holding shift to go down at the same time it thinks you sneaked to fast.

**Comment by gravitylow** [comment]
Fixed as of dev #121 http://ci.h31ix.net/job/AntiCheat/121/
