### ISSUE TITLE
Permissions won't work(GM)

### ISSUE THREAD

**Issue by jbanto** [gravitylow/AntiCheat#81]
Hi, I'm not sure if this is a bug or not but I cant get permissions to work.

-Craftbukkit 1.2.5 R4.0
-Essentials Group Manager 2.9.1 /w Vault
-AntiCheat 1.3.1

Install went fine, didn't throw any errors on console, didn't change any config or anything. I gave mods the mod permission and admins the admin permission, that didn't work(got the no permission message), then I gave myself the "anticheat._" , still didnt work, tried just "_" and that didnt work either, but it works for ops and console. I also tried re-downloading a fresh anticheat.jar. I used AntiCheat before (switched to nocheat+ hehe) and it worked fine with the general "*" node.

**Comment by gravitylow** [comment]
Use the latest dev build. http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/
