### ISSUE TITLE
Enchanted bows trigger (projectile?) check

### ISSUE THREAD

**Issue by cuddylier** [gravitylow/AntiCheat#82]
Hi

In the latest recommended build if you use enchanted items such as fully enchanted bows, it says you are trying to fire too fast.

**Comment by SuperSpyTX** [comment]
Logs?

**Comment by SuperSpyTX** [comment]
Nevermind.  It sounds like a bug to me.  I'll have @h31ix look at this.

But otherwise, I'm updating the issue title to reflect the issue entirely.

**Comment by cuddylier** [comment]
Thanks

**Comment by gravitylow** [comment]
What enchantment?

**Comment by cuddylier** [comment]
It was a bow with all enchantments but I think the power enchantment. On the pickaxes the efficiency enchantment seems to trigger fastbreak. Also sometimes randomly, anticheat thinks people are fast placing when they are not. Finally, the anti command spam feature is far too sensitive, I think everyone out of my 60

**Comment by cuddylier** [comment]
...players got kicked within 10 minutes.

**Comment by gravitylow** [comment]
Uising the latest dev? We fixed a bunch of command/chat spam issues in them.

**Comment by SuperSpyTX** [comment]
Sounds outdated build.  Update to latest dev and report back.
