### ISSUE TITLE
NO reason

### ISSUE THREAD

**Issue by baconkilla2** [gravitylow/AntiCheat#83]
Anti cheat causes people to lag for no reason even if they completely uninstall there cheating mods, and or clients.

**Comment by gravitylow** [comment]
Way too vague. We need actual logs, build number, and a better description of the issue better than "lagging".

**Comment by baconkilla2** [comment]
Ok sorry for being. Vague. Here is the issue. I was using the version for bukkit 1.0 mc version 1.2.5. My friend was testing anti cheat out on my server by using private clients and hacks. After some time the anticheat started making him lag and saying that his hack level was high. So then he uninstalled all his mods and private clients. Then he got back on and anticheat still was making him lag saying he has a high hack level. The only way i stopped this was by uninstalling anti cheat.

**Comment by gravitylow** [comment]
So he was cheating, and the only person who was getting bugged was the cheater? AntiCheat remembers your hack level, dude, so if the only person who was getting annoyed was someone who was previously hacking, I have no intention of looking into that.

**Comment by baconkilla2** [comment]
Yes but even when he uninstalled the hacks anticheat was still giving him trouble. He wasnt hacking but anticheat was troubling him.

**Comment by gravitylow** [comment]
Delete your AntiCheat folder, then retry. If it's only one person, it's an issue with that person.
