### ISSUE TITLE
Silent Mode

### ISSUE THREAD

**Issue by SuperSpyTX** [gravitylow/AntiCheat#85]
This would be a huge benefit to many server owners if they had the ability to operate AntiCheat in "silent mode".

As much as we love AntiCheat to stop players from hacking, it's probably beneficial to have a mode where AntiCheat does not intervene with the player if they are hacking nor message the player if they are.

Split it up into two options:
Silent Mode:
     DontIntervenePlayer: true
     DontMessagePlayer: true

My configuration values should **not** be in there, make something up.

**Comment by gravitylow** [comment]
Added.
