### ISSUE TITLE
False Speed hack

### ISSUE THREAD

**Issue by RustyDagger** [gravitylow/AntiCheat#86]
A number of my players and my self have noticed that the plugin is resetting us when we sprint and jump Like jump a lot.

This is messing up our parkour games as users can't run and jump like they need to. We are running the latest version.
I clearly do not think giving them the bypass is the answer.

**Comment by gravitylow** [comment]
Latest version as in latest dev build? Can I please see logs?

**Comment by RustyDagger** [comment]
Sure Ill just go dig them up and ill make sure I have the latest dev before doing so.

EDIT -------------------------------------------------------------------------------------

Updated to latest dev Build 204. Now unable to reproduce The issue Will see if users still complain at me tomorrow when they are online again. 

Was even trying to force the plugins hand by increasing my lag by uploading  still good double checked my permissions I have no bypass.
