### ISSUE TITLE
AntiCheat causing a lot delay on server with 100+ players

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#88]
Here are my timings: http://pastebin.com/gnJyTT1P
As you can see i pasted the timings from other plugins under it.
And none of the plugins are going above AntiCheat.
And this is only 3 hours after i reset it.
And i runned on the same server NoCheat and waited 3 hours +/- same amount of players and it had a total time of 9s
This is really not good and it's causing lots of issues on my server.
I switched to AntiCheat a little ago because i thought it had better performance but if this wont be fixed i guess i have to go back to NoCheat.
So please look into it and see if it can be fixed.
I didn't had this issues in the beginning btw think it started about 1<>2 weeks ago don't have a exact date and build numbers.

**Comment by SuperSpyTX** [comment]
Wait a hour, I will ask you to use the new devbuild and test out a new feature as well.

**Comment by Rojoss** [comment]
Alright hope it will fix the lag/delay.

**Comment by SuperSpyTX** [comment]
Alrighty, let's use it to help you and I.

First off, go ahead and download this build: http://ci.h31ix.net/job/AntiCheat/208/

Next, when things start to get laggy, type /anticheat pastebin either ingame or in the console.  You should get a URL, copy the URL and paste it into this issue.

I'm looking forward to results.

**Comment by Rojoss** [comment]
Alright adding it to my servers and will let it run when it's starting to lag.

**Comment by Rojoss** [comment]
http://pastebin.com/SWdMcqmc

**Comment by SuperSpyTX** [comment]
How many plugins are you running by any chance?

**Comment by Rojoss** [comment]
51

**Comment by SuperSpyTX** [comment]
Alrighty, I've done some conclusions and this seems to be the case.

Because you run 2 servers, I will be speaking in combined totals.

Thanks to Dinnerbone's status checker, I was able to determine that you run about 100 plugins (99), and offer 200 slots to everybody while running on 16GB RAM.  As much as you think that sounds pretty lightweight, i disagree that Falsebook sounds pretty lightweight as well.

As much as for me to tell you that you are running too many plugins and offering too many slots, I can (probably) help you if you do the following:
- Install NoLagg, then ingame while players are on, type /nolagg examine on both servers.  Upload the exam file that will be located in your plugins folder to some place (won't be pastebinable), possibly mediafire.com.

Return here with a mediafire link to your exam files and I'll investigate on which plugin is causing lag.

**Comment by SuperSpyTX** [comment]
After taking a look at the logs, I think some garbage cleanup should be done if a player's kicked/disconnects.

This way it should reduce lag.

**Comment by Rojoss** [comment]
Well you might say the servers aren't strong enough but they defiantly are.
It's running on a Intel Xeon E3-1270 3,4GHZ
And enough ram and ram doesn't mean that much though.
Also im gonna say nolagg is crap and im not going to install it.
I really don't understand others can say it's good it's not.
Without AntiCheat the server is running 100% smooth no lagg at all even with 100 players online.
And Falsebook is a really bad example only FalseBook ic is heavy core is completely not.
All it does is combinating the plugins together and im only having FalseBook Block that have Gates/Bridges etc.
That's completely not heavy it only create events when players use it.
I understand anti hacking plugins are heavy and it wont be able to have 0 timings and everything.
But compared to the other plugins almost 60s in 3 hours is really ridiculous. 
Even NoCheat++ have lower timings then this and that plugin is more buggy and got way more features then this.
Before it had low timinings and my server never lagged.
But since 1/2  weeks it's buggy having huge timings and causing lag on my server.

**Comment by gravitylow** [comment]
Try the newer builds worstboy, we worked on a bit on this. If the server starts getting laggy type /anticheat pastebin and give us the output.

**Comment by Rojoss** [comment]
Alright will do

**Comment by Rojoss** [comment]
Anyway it's not fixed the timings are even worse now.
This timings are from 6 hours server running  with the other timings from 3 hours you should expect it 100<>150s
But it's over 200 now so it did get even worse.
http://pastebin.com/DrrWR26k
Also the lag issues aren't fixed players are still getting lag.

I'm also running a Dwarves VS Zombies server
I tried 1 round with this build of AntiCheat and everyone was complaining about lag and glitchy
And then i tried 1 round with NoCheat++ and nobody complaining about lag.
That server only got about 15 plugins and there where like 80 players online both rounds.

**Comment by gravitylow** [comment]
I said we need the output of /anticheat pastebin, please.

**Comment by Rojoss** [comment]
http://pastebin.com/ksF1EpNy

**Comment by gravitylow** [comment]
Ahaha.. Well thanks @worstboy32 I think that helped us determine a huge issue; we've been inserting players multiple times into lists and stuff without checking if they are in it first. Fixing that might help a lot with heap size and stuff. Try out http://ci.h31ix.net/job/AntiCheat/215/

**Comment by Rojoss** [comment]
Thanks for this will test it and comment back if it fixed the issues or if it didn't.

EDIT: Seems to fix a lot lag.
Will wait a few hours and make a new timings/report.

**Comment by Rojoss** [comment]
Pretty sure it's fixed.
The lag is gone and the debug pastebin don't have that much names anymore.
But the timings are still pretty high though but i can live with it for not.
It's not as bad as it was :)
thanks for your help h31ix!
