### ISSUE TITLE
Trapdoor on top of chest causes visuals failure.

### ISSUE THREAD

**Issue by Spezialeinheit** [gravitylow/AntiCheat#89]
http://www.youtube.com/watch?v=XN4igaduao0

**Comment by SuperSpyTX** [comment]
I love that you recorded a video n all, but check issue #80 before you make a ticket.

Nonetheless, since because I referenced the other issue, it will post a link back here at a later time.

However, this means i'm closing this.

**Comment by SuperSpyTX** [comment]
To update this issue, it's been officially fixed in the latest devbuild.
