### ISSUE TITLE
Moving on y coordinates on Enderpearl use and Teleport.

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#9]
When players are using enderpearls they are getting warnings for flying on y axis.
And also when players use as example /spawn they get warned.
But after that they also glitch in the floor and in this example spawn is a safe location but /home as example not.
That means players lose often all there items they had and is really annoying.
Also using FalseBook and lift signs are having the same issue as teleporting.

**Comment by Rojoss** [comment]
Sorry duplicate just saw closed issues.

**Comment by Rojoss** [comment]
Wanna reopen this since the last dev version is still punishing players for teleporting.
Hope this can be sorted out since i can't just disable fly checks it's like for every command that teleport a player.
Not only /spawn and /home but many others.
And we have a custom punishing plugin and when i set it to jail then when the player get jailed by AntiCheat then he falls through the ground or don't even get tped :s
It's really buggy with the y axis.

**Comment by gravitylow** [comment]
If you have multiple bugs, please split them up into issues so we can keep track and name them appropriately.

**Comment by Rojoss** [comment]
It's all about the same..
It's about the y axis flying.
When it happen the player don't only get a warning but also fall in the ground and die.

**Comment by gravitylow** [comment]
You were also talking about the jail issue, which seems to be unrelated. Could you paste the warning they get please?

**Comment by Rojoss** [comment]
http://files.enjin.com.s3.amazonaws.com/122572/modules/forum/attachments/2012-05-28_21.47.31_1338257247.png

Will post a new issue for the jail but we might be able to fix it self will look into that first if that don't work i will make one.

**Comment by gravitylow** [comment]
We believe this to be fixed in http://ci.h31ix.net/job/AntiCheat/131/, please test and reply back so we can close or keep this open.

**Comment by Rojoss** [comment]
Testing it now will close when it's 100% working so far looking good.

EDIT: Closing it since it seems to be fixed :)
Thanks
