### ISSUE TITLE
I'm a madbro

### ISSUE THREAD

**Issue by nejcneo** [gravitylow/AntiCheat#90]
Sorry but I thing that this plugin is Crap, no seriusly !
Try it on yourserver.
I tryed it and users were saying that they can't chat because they get error: "don't spam" WTF ?
End I tried walk on stairs and Get kicked because hacking,

Lol I think you should give advantage to NoCheat+
You put 200+ Dev builds and still shit xD, It sould work after 3 Builds, not 200

EDIT

Try it on your own server and see thet is crap

**Comment by gravitylow** [comment]
Lol'ed hard. Go away, and at least learn to spell before you insult someone. https://github.com/h31ix/AntiCheat/issues/87
