### ISSUE TITLE
2 found bugs ( Opening chests on top and landing after fly )

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#91]
Here 2 bugs with AntiCheat
When you land when your in gm then it push you back and you get some times kicked.
When you try open a chest it blocks it and u get kicked.
Here quick video that show the bugs:
http://www.youtube.com/watch?v=lxT12GlXg_k

**Comment by SuperSpyTX** [comment]
I need more information on the first "bug".  When you have details, head over to issue #80 and follow the form.

The landing after fly issue can't be done until bukkit releases a new RB with a new event "PlayerToggleFlyEvent".

EDIT: It's a duplicate because the second issue is known.
