### ISSUE TITLE
People kicked for standing still, commands won't go through

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#92]
When people stand still on my server for an extended period of time, say, when theyre fishing, it for some reason kicks them 'for flying'

Also, when someone uses the same command multiple times in succession, it doesn't let them use it and says 'please do not spam' or something along those lines.

Both of these bugs have been extremely annoying, but I solved them by giving my groups the permission to fly and spam temporarily until this is fixed.

**Comment by SuperSpyTX** [comment]
Sounds like an /extremely/ outdated build.

Reply to this ticket at anytime when you go ahead and try the latest build.
