### ISSUE TITLE
[Point] signs usage blocked by AntiCheat

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#94]
I'm running a plugin called PointShop and the sign is [Points]
And players can't interact with it it will kick them.
They can use it 1 time and then when they try use it again multiple times they will be punished.
Also for [Join] signs for one of our custom plugins but that's not a big issues since that only need to be used 1 time.
Maybe add custom signs in config.
Pretty sure other plugins also have intractable signs.

**Comment by gravitylow** [comment]
Is this still an issue in the new version you installed?

**Comment by Rojoss** [comment]
Yes

**Comment by gravitylow** [comment]
I can't replicate on b216. Can you send me logs and a picture of what the setup looks like?

**Comment by gravitylow** [comment]
See http://ci.h31ix.net/job/AntiCheat/219/

**Comment by Rojoss** [comment]
Works.
Thanks for the fix.
