### ISSUE TITLE
Interacting with levers result in false positive kicks with small objects in blocks

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#96]
Working levers with objects small objects in between will kick the player that is not hacking.  Examples: redstone and stone buttons.

Example, put a lever on top of a block 4 meters in front of you, so the lever is eye-level.  Please a stone button on the front of the block under the lever.  Interacting with the lever can result in false positive if you are not very close.  Same for redstone along the ground from your feet to the block under the lever.

I have a couple of screen shots of the actual scenario if you can't reproduce it.

**Comment by gravitylow** [comment]
Check out http://ci.h31ix.net/job/AntiCheat/219/
