### ISSUE TITLE
Permissions not working correctly?

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#97]
I personally enjoy using PermissionsEx, but after the permissions change to make it easier on yourself and everyone else, my staff team does not receive any more alert messages. This change was in build #184-187. 

Yes, they have the correct permissions. 

anticheat.alert for both groups;
anticheat.mod for moderators;
& anticheat.admin for admins.

But only I receive the alerts via console and in-game because I am an op. I am currently using build #219 and hope that this issue would be looked into soon.

**Comment by cuddylier** [comment]
Are you using latest dev build? Those permission nodes work fine for me on permissionsex.

**Comment by ghost** [comment]
I am, yes. Admins are unable to view in-game reports. =/
