### ISSUE TITLE
Anticheat permissions bug -- Anyone receives xray reports regardless if they have the permission or not.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#99]
Using anticheat #222, everyone seems to receive the xray report, even members who don't have the permission to view them. Also, staff members with the permission anticheat.mod and anticheat.admin still don't receive error reports in-game, while console gets spammed with them. :(

Off topic issue, it seems some users get the "placing blocks too fast/destroying blocks too fast" message more than others, most likely due to latency or a minor spike on their end. Is there a way to tweak it to not be as sensitive?

**Comment by ghost** [comment]
It also seems that now everyone is receiving anticheat reports, not just staff.

**Comment by gravitylow** [comment]
By "reports" do you mean "x tried to xxxx too fast" messages or something? Because that's the only thing the console gets "spammed" with. Players will not get these; it's too spammy. They will only get messages when a player moves levels.

**Comment by ghost** [comment]
Using build #223, everyone still gets reports from anticheat xray. Regardless if they have the permission or not.

**Comment by gravitylow** [comment]
Well, you can check out the code, it's really as clear as can possibly be..

https://github.com/h31ix/AntiCheat/blob/master/src/main/java/net/h31ix/anticheat/util/Utilities.java#L42
The alert function we use loops through every player on the server, then does a superperms call to see if they have permission. Any modern permissions plugin does support superperms. It's only at that point that they are sent the message.

I'm really inclined to close this seeing as the only reason something could happen like that is because of a permissions error; you've either given people anticheat.alert, anticheat.mod, anticheat.admin, or anticheat.*.

**Comment by ghost** [comment]
I can assure you that I have not given anyone those permissions other than my staff members. No group is linked to the staff ranks so they do not inherit the group's permissions. I triple checked every permission in all groups and again, I assure you they do not have any anti-cheat permission node.

I am also using the latest development build of PermissionsEx, which can be found here.
http://webbukkit.org:8080/job/PermissionsEx/

This issue never arose until the permission changes took place. I am no rookie when it comes to configuring permissions, my server has been up for 2 years.

Unless this change has something to do with a code break, https://github.com/PEXPlugins/PermissionsEx/commit/19cfefb7920014bdf66c58db134f2fd71d64f861 , then the issue has to be on AntiCheat's side.

Maybe if there was a way to only loop through players if they have a certain permission? Because as stated in the original post, all users are seeing xray reports and hacking/lagging reports.

**Comment by SuperSpyTX** [comment]
Reset your permissions configuration, then come back, and start over with them.

I'm too inclined to close this.....But, I...:'(

**Comment by Rojoss** [comment]
I second this.
Everyone gets the message when someone enter medium or high hack level.
And even the xray warnings.
And also i am 100% sure that they don't have any AntiCheat permissions.

**Comment by ghost** [comment]
Glad someone else is experiencing this issue. Please reopen this ticket and investigate SuperSpyTX.

**Comment by SuperSpyTX** [comment]
Everyone try http://ci.h31ix.net/job/AntiCheat/226/

Thanks.

**Comment by ghost** [comment]
Attempting to use it now. So far, don't see any reports/xray reports but I'll let you know if I do and let you know if others report about seeing it.

**Comment by gravitylow** [comment]
Fixed in 1.3.3
